# Changes here will be overwritten by Copier
_commit: 2025.09.19
_src_path: gh:zenml-io/template-llm-finetuning
bf16: true
cuda_version: cuda11.8
dataset_name: gem/viggo
email: info@zenml.io
full_name: ZenML GmbH
model_repository: microsoft/phi-2
open_source_license: apache
product_name: llm-peft
project_name: ZenML LLM Finetuning project
step_operator: gcp_a100
steps_of_finetuning: 300
system_prompt: 'Given a target sentence construct the underlying meaning representation
    of the input sentence as a single function with attributes and attribute values.

    This function should describe the target string accurately and the function must
    be one of the following [''inform'', ''request'', ''give_opinion'', ''confirm'',
    ''verify_attribute'', ''suggest'', ''request_explanation'', ''recommend'', ''request_attribute''].

    The attributes must be one of the following: [''name'', ''exp_release_date'',
    ''release_year'', ''developer'', ''esrb'', ''rating'', ''genres'', ''player_perspective'',
    ''has_multiplayer'', ''platforms'', ''available_on_steam'', ''has_linux_release'',
    ''has_mac_release'', ''specifier'']

    '
use_fast_tokenizer: false
version: 0.1.0
zenml_server_url: ''
