---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
      timezone: Europe/Amsterdam
    reviewers: [strickvl]
    labels: [dependencies, internal, no-release-notes]
    groups:
      all-actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    target-branch: develop
