steps:
  # login to Dockerhub
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker login --username=$$USERNAME --password=$$PASSWORD
    id: docker-login
    entrypoint: bash
    secretEnv:
      - USERNAME
      - PASSWORD

  # Build base image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker build . \
          --platform linux/amd64 \
          -f docker/zenml-dev.Dockerfile \
          -t $$USERNAME/zenml-dev:${_ZENML_BRANCH_NAME}

    id: build-base
    waitFor: ['-']
    entrypoint: bash
    secretEnv:
      - USERNAME

  # Push base image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker push $$USERNAME/zenml-dev:${_ZENML_BRANCH_NAME}
    id: push-base
    waitFor:
      - docker-login
      - build-base
    entrypoint: bash
    secretEnv:
      - USERNAME

  # Build server image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker build . \
          --platform linux/amd64 \
          -f docker/zenml-server-dev.Dockerfile \
          -t $$USERNAME/zenml-server-dev:${_ZENML_BRANCH_NAME}

    id: build-server
    waitFor: ['-']
    entrypoint: bash
    secretEnv:
      - USERNAME

  # Push server image
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker push $$USERNAME/zenml-server-dev:${_ZENML_BRANCH_NAME}
    id: push-server
    waitFor:
      - docker-login
      - build-server
    entrypoint: bash
    secretEnv:
      - USERNAME

timeout: 3600s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/1
      env: PASSWORD
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/1
      env: USERNAME 