M	README.md
D	examples/minimal_agent_production/README.md
D	examples/minimal_agent_production/__init__.py
D	examples/minimal_agent_production/app/__init__.py
D	examples/minimal_agent_production/app/main.py
D	examples/minimal_agent_production/llm_utils.py
D	examples/minimal_agent_production/models.py
D	examples/minimal_agent_production/pipelines/__init__.py
D	examples/minimal_agent_production/pipelines/evaluation.py
D	examples/minimal_agent_production/pipelines/production.py
D	examples/minimal_agent_production/requirements.txt
D	examples/minimal_agent_production/run_evaluation.py
D	examples/minimal_agent_production/run_production.py
D	examples/minimal_agent_production/steps/__init__.py
D	examples/minimal_agent_production/steps/analyze.py
D	examples/minimal_agent_production/steps/evaluate.py
D	examples/minimal_agent_production/steps/ingest.py
D	examples/minimal_agent_production/steps/render.py
D	examples/minimal_agent_production/steps/utils.py
M	pyproject.toml
