{{- range $ca := .Values.zenml.certificates.customCAs }}
{{- range $cm := list (dict "suffix" "") (dict "suffix" "-db-migration" "isDbMigration" true) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "zenml.fullname" $ }}-custom-ca-{{ $ca.name }}{{ $cm.suffix }}
  labels:
    {{- include "zenml.labels" $ | nindent 4 }}
  {{- if $cm.isDbMigration }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-3"  
    "helm.sh/hook-delete-policy": before-hook-creation{{ if not $.Values.zenml.debug }},hook-succeeded{{ end }}
  {{- end }}
data:
  certificate: {{ $ca.certificate | b64enc | quote }}
{{- end }}
{{- end }}
