{{- if .Values.zenml.ingress.enabled -}}
{{- $fullName := include "zenml.fullname" . -}}
{{- $svcPort := .Values.zenml.service.port -}}
{{- if and .Values.zenml.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.zenml.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.zenml.ingress.annotations "kubernetes.io/ingress.class" .Values.zenml.ingress.className}}
  {{- end }}
{{- end }}
{{- if and $.Values.zenml.ingress.tls.enabled (eq .Values.zenml.ingress.className "nginx") }}
  {{- $_ := set .Values.zenml.ingress.annotations "nginx.ingress.kubernetes.io/ssl-redirect" "true"}}
{{- end }}

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
  {{- with .Values.zenml.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.zenml.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.zenml.ingress.className }}
  {{- end }}
  {{- if .Values.zenml.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.zenml.ingress.host | quote }}
      secretName: {{ .Values.zenml.ingress.tls.secretName }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.zenml.ingress.path }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
      {{- if .Values.zenml.ingress.host }}
      host: {{ .Values.zenml.ingress.host | quote }}
      {{- end }}
{{- end }}
