{{- $server := include "zenml.serverValues" . | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenml.fullname" . }}
  labels:
    {{- include "zenml.labels" . | nindent 4 }}
  {{- with $server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $server.service.type }}
  ports:
    - port: {{ $server.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "zenml.serverSelectorLabels" . | nindent 4 }}
