root: .
structure:
  readme: component-guide.md
  summary: toc.md

redirects:
  alerters: alerters/README.md
  alerters/custom: alerters/custom.md
  alerters/discord: alerters/discord.md
  alerters/slack: alerters/slack.md
  annotators: annotators/README.md
  annotators/argilla: annotators/argilla.md
  annotators/custom: annotators/custom.md
  annotators/label-studio: annotators/label-studio.md
  annotators/pigeon: annotators/pigeon.md
  annotators/prodigy: annotators/prodigy.md
  artifact-stores: artifact-stores/README.md
  artifact-stores/azure: artifact-stores/azure.md
  artifact-stores/custom: artifact-stores/custom.md
  artifact-stores/gcp: artifact-stores/gcp.md
  artifact-stores/local: artifact-stores/local.md
  artifact-stores/s3: artifact-stores/s3.md
  container-registries: container-registries/README.md
  container-registries/aws: container-registries/aws.md
  container-registries/azure: container-registries/azure.md
  container-registries/custom: container-registries/custom.md
  container-registries/default: container-registries/default.md
  container-registries/dockerhub: container-registries/dockerhub.md
  container-registries/gcp: container-registries/gcp.md
  container-registries/github: container-registries/github.md
  data-validators: data-validators/README.md
  data-validators/custom: data-validators/custom.md
  data-validators/deepchecks: data-validators/deepchecks.md
  data-validators/evidently: data-validators/evidently.md
  data-validators/great-expectations: data-validators/great-expectations.md
  data-validators/whylogs: data-validators/whylogs.md
  experiment-trackers: experiment-trackers/README.md
  experiment-trackers/comet: experiment-trackers/comet.md
  experiment-trackers/custom: experiment-trackers/custom.md
  experiment-trackers/mlflow: experiment-trackers/mlflow.md
  experiment-trackers/neptune: experiment-trackers/neptune.md
  experiment-trackers/vertexai: experiment-trackers/vertexai.md
  experiment-trackers/wandb: experiment-trackers/wandb.md
  feature-stores: feature-stores/README.md
  feature-stores/custom: feature-stores/custom.md
  feature-stores/feast: feature-stores/feast.md
  image-builders: image-builders/README.md
  image-builders/aws: image-builders/aws.md
  image-builders/custom: image-builders/custom.md
  image-builders/gcp: image-builders/gcp.md
  image-builders/kaniko: image-builders/kaniko.md
  image-builders/local: image-builders/local.md
  model-deployers: model-deployers/README.md
  model-deployers/bentoml: model-deployers/bentoml.md
  model-deployers/custom: model-deployers/custom.md
  model-deployers/databricks: model-deployers/databricks.md
  model-deployers/huggingface: model-deployers/huggingface.md
  model-deployers/mlflow: model-deployers/mlflow.md
  model-deployers/seldon: model-deployers/seldon.md
  model-deployers/vllm: model-deployers/vllm.md
  model-registries: model-registries/README.md
  model-registries/custom: model-registries/custom.md
  model-registries/mlflow: model-registries/mlflow.md
  orchestrators: orchestrators/README.md
  orchestrators/airflow: orchestrators/airflow.md
  orchestrators/azureml: orchestrators/azureml.md
  orchestrators/custom: orchestrators/custom.md
  orchestrators/databricks: orchestrators/databricks.md
  orchestrators/hyperai: orchestrators/hyperai.md
  orchestrators/kubeflow: orchestrators/kubeflow.md
  orchestrators/kubernetes: orchestrators/kubernetes.md
  orchestrators/lightning: orchestrators/lightning.md
  orchestrators/local: orchestrators/local.md
  orchestrators/local-docker: orchestrators/local-docker.md
  orchestrators/sagemaker: orchestrators/sagemaker.md
  orchestrators/skypilot-vm: orchestrators/skypilot-vm.md
  orchestrators/tekton: orchestrators/tekton.md
  orchestrators/vertex: orchestrators/vertex.md
  step-operators: step-operators/README.md
  step-operators/azureml: step-operators/azureml.md
  step-operators/custom: step-operators/custom.md
  step-operators/kubernetes: step-operators/kubernetes.md
  step-operators/modal: step-operators/modal.md
  step-operators/sagemaker: step-operators/sagemaker.md
  step-operators/spark-kubernetes: step-operators/spark-kubernetes.md
  step-operators/vertex: step-operators/vertex.md