---
name: Feature Request
description: Suggest a new feature or enhancement
type: Feature
labels: [core-team]
projects: [zenml-io/1]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Your ideas help make ZenML better.
  - type: input
    id: contact
    attributes:
      label: Contact Details [Optional]
      description: How can we get in touch with you if we need more info?
      placeholder: youre@awesome.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added to ZenML?
      placeholder: A clear and concise description of the feature you'd like to see
        implemented.
    validations:
      required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it enable?
      placeholder: Describe the problem you're trying to solve or the workflow you're
        trying to enable.
    validations:
      required: false
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your ideal solution and how users would interact with
        it.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, examples, or implementation ideas.
      placeholder: Screenshots, code examples, links to similar features, etc.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE-OF-CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
