"""GRPO training step: one optimizer pass over the iteration's episodes."""

import math
import os
import tempfile
import time
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional

from zenml import log_metadata, step


@step
def grpo_update(
    episodes: List[Dict[str, Any]],
    adapter: Path,
    model_name: str,
    group_size: int,
    learning_rate: float = 5e-6,
) -> Path:
    """Run one GRPO optimizer step over pre-generated, pre-scored episodes.

    TRL is used as a library, not an orchestrator: the experimental
    `rollout_func` hook returns the episodes generated by
    `generate_rollouts` and scored by `run_episode`, so GRPOTrainer only
    owns the math (advantages, loss, gradient step). Verified against TRL
    1.7.1 — note that despite TRL's docstring, `rollout_func` receives
    each prompt already repeated num_generations times and must return
    exactly one completion per received entry.

    Args:
        episodes: Scored episode dicts (reward field present).
        adapter: Current LoRA adapter directory.
        model_name: HF model ID of the policy base model.
        group_size: GRPO group size; must match generation.
        learning_rate: Optimizer learning rate.

    Returns:
        Path to the updated adapter directory (the next iteration's
        policy).

    Raises:
        ValueError: If episodes don't form complete groups.
        RuntimeError: If training produced non-finite weights (the
            adapter must not be saved or the corruption propagates to
            every later iteration).
    """
    os.environ["TRL_EXPERIMENTAL_SILENCE"] = "1"

    import torch
    from datasets import Dataset
    from peft import PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from trl import GRPOConfig, GRPOTrainer

    started_total = time.time()

    # Group episodes by prompt, ordered by rollout index within the group.
    by_prompt: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for episode in episodes:
        by_prompt[episode["prompt_text"]].append(episode)
    for group in by_prompt.values():
        group.sort(key=lambda e: e["rollout_index"])
        if len(group) != group_size:
            raise ValueError(
                f"Task group has {len(group)} episodes, expected "
                f"{group_size}. Episodes lost between generation and "
                "training?"
            )
    unique_prompts = list(by_prompt.keys())

    started = time.time()
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    # bf16 on CUDA (halves GPU memory for the 4B model — fits the 24GB
    # L4 with room for activations); float32 on CPU/MPS where bf16 is
    # slow or flaky.
    dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32
    base_model = AutoModelForCausalLM.from_pretrained(model_name, dtype=dtype)
    model = PeftModel.from_pretrained(
        base_model, str(adapter), is_trainable=True
    )
    model_load_seconds = round(time.time() - started, 2)

    # One completion per received prompt entry; the cursor walks each
    # group in rollout order as TRL asks for that prompt again.
    cursor: Dict[str, int] = defaultdict(int)

    def rollout_func(prompts: List[Any], trainer: Any) -> Dict[str, List[Any]]:
        out: Dict[str, List[Any]] = {
            "prompt_ids": [],
            "completion_ids": [],
            "logprobs": [],
            "reward": [],
        }
        for prompt in prompts:
            episode = by_prompt[prompt][cursor[prompt]]
            cursor[prompt] += 1
            out["prompt_ids"].append(episode["prompt_ids"])
            out["completion_ids"].append(episode["completion_ids"])
            out["logprobs"].append(episode["logprobs"])
            out["reward"].append(episode["reward"])
        return out

    def precomputed_reward(
        completions: List[Any],
        reward: Optional[List[float]] = None,
        **kwargs: Any,
    ) -> List[float]:
        # Rewards were computed in the sandbox; TRL just gets them back
        # via the rollout_func extra field.
        assert reward is not None
        return [float(r) for r in reward]

    config = GRPOConfig(
        output_dir=tempfile.mkdtemp(prefix="rl-spike-grpo-"),
        per_device_train_batch_size=group_size,
        gradient_accumulation_steps=len(unique_prompts),
        num_generations=group_size,
        max_steps=1,
        learning_rate=learning_rate,
        beta=0.0,  # no KL term -> no reference model in memory
        report_to=[],
        logging_steps=1,
        # Prefer any accelerator: CUDA on the cluster, MPS on Apple
        # Silicon laptops (the dry-run training step is ~10x slower on
        # pure CPU).
        use_cpu=not (
            torch.cuda.is_available() or torch.backends.mps.is_available()
        ),
    )
    trainer = GRPOTrainer(
        model=model,
        reward_funcs=precomputed_reward,
        args=config,
        train_dataset=Dataset.from_dict({"prompt": unique_prompts}),
        processing_class=tokenizer,
        rollout_func=rollout_func,
    )

    started = time.time()
    train_result = trainer.train()
    train_seconds = round(time.time() - started, 2)

    grad_norm = next(
        (
            entry["grad_norm"]
            for entry in reversed(trainer.state.log_history)
            if "grad_norm" in entry
        ),
        None,
    )

    # Fail LOUDLY on numerical corruption. Unlike episode failures (which
    # are legitimately reward=0), a non-finite update poisons every
    # subsequent iteration — a green run that ships a NaN adapter is the
    # worst outcome (we shipped exactly that once; see BREAKAGE_LOG
    # entry 7's postscript).
    corrupted = [
        name
        for name, parameter in model.named_parameters()
        if parameter.requires_grad and not torch.isfinite(parameter).all()
    ]
    if corrupted:
        raise RuntimeError(
            f"grpo_update produced non-finite weights in {len(corrupted)} "
            f"tensors (grad_norm={grad_norm}); refusing to save the "
            f"adapter. First corrupted: {corrupted[:3]}"
        )

    new_adapter_dir = (
        Path(tempfile.mkdtemp(prefix="rl-spike-adapter-")) / "adapter"
    )
    trainer.model.save_pretrained(str(new_adapter_dir))

    if grad_norm is not None and not math.isfinite(grad_norm):
        # A non-finite gradient norm means TRL's clipping zeroed this
        # update (clip coefficient max_norm/inf = 0): the adapter passes
        # through unchanged. Warn loudly but keep going — the weights are
        # valid, and on MPS this happens sporadically with the dry run's
        # deliberately off-policy canned completions (see
        # IMPLEMENTATION_NOTES deviation 1).
        print(
            f"WARNING: non-finite grad_norm ({grad_norm}) — this "
            "optimizer update was zeroed by gradient clipping."
        )

    def json_safe(value: float) -> "float | str":
        # ZenML's metadata endpoint rejects IEEE inf/NaN at the HTTP
        # layer (BREAKAGE_LOG entry 9); stringify non-finite floats.
        return value if math.isfinite(value) else str(value)

    rewards = [e["reward"] for e in episodes]
    log_metadata(
        metadata={
            "num_episodes": len(episodes),
            "num_groups": len(unique_prompts),
            "mean_reward": round(sum(rewards) / len(rewards), 4),
            "train_loss": json_safe(float(train_result.training_loss)),
            "grad_norm": (
                json_safe(float(grad_norm)) if grad_norm is not None else -1.0
            ),
            "model_load_seconds": model_load_seconds,
            "train_seconds": train_seconds,
            "wall_clock_seconds": round(time.time() - started_total, 2),
            "learning_rate": learning_rate,
        }
    )
    return new_adapter_dir
