# Export Terraform output variable values to a stack yaml file 
# that can be consumed by zenml stack import
resource "local_file" "stack_file" {
  content  = <<-ADD
    # Stack configuration YAML
    # Generated by the Azure Minimal MLOps stack recipe.
    zenml_version: ${var.zenml-version}
    stack_name: azure_minimal_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}
    components:
      artifact_store:
        id: ${uuid()}
        flavor: azure
        name: azure_artifact_store
        configuration: {"path": "az://${azurerm_storage_container.artifact-store.name}", "authentication_secret": "azure-storage-secret"}
      container_registry:
        id: ${uuid()}
        flavor: azure
        name: acr_container_registry
        configuration: {"uri": "${azurerm_container_registry.container_registry.login_server}"}
      orchestrator:
        id: ${uuid()}
        flavor: kubernetes
        name: aks_kubernetes_orchestrator
        configuration: {"kubernetes_context": "${local.kubectl_context}", "synchronous": True}
      secrets_manager:
        id: ${uuid()}
        flavor: azure_key_vault
        name: azure_secrets_manager
        configuration: {"key_vault_name": "${azurerm_key_vault.secret_manager.name}"}
      experiment_tracker:
        id: ${uuid()}
        flavor: mlflow
        name: aks_mlflow_experiment_tracker
        configuration: {"tracking_uri": "http://${data.kubernetes_service.mlflow_tracking.status.0.load_balancer.0.ingress.0.ip}", "tracking_username": "${var.mlflow-username}", "tracking_password": "${var.mlflow-password}"}
      model_deployer:
        id: ${uuid()}
        flavor: seldon
        name: aks_seldon_model_deployer
        configuration: {"kubernetes_context": "${local.kubectl_context}", "kubernetes_namespace": "${kubernetes_namespace.seldon-workloads.metadata[0].name}", "base_url": "${data.kubernetes_service.seldon_ingress.status.0.load_balancer.0.ingress.0.ip}", "secret": "azure-seldon-secret"}
    ADD
  filename = "./azure_minimal_stack_${replace(substr(timestamp(), 0, 16), ":", "_")}.yaml"
}