#  Copyright (c) ZenML GmbH 2022. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied. See the License for the specific language governing
#  permissions and limitations under the License.
"""Implementation of the S3 Artifact Store."""

import os
import posixpath
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
from typing import (
    Any,
    Callable,
    Dict,
    Generator,
    Iterable,
    List,
    Optional,
    Sequence,
    Tuple,
    Union,
    cast,
)

import boto3
import s3fs
from boto3.s3.transfer import TransferConfig
from botocore.config import Config
from botocore.exceptions import ClientError
from fsspec.asyn import FSTimeoutError, sync, sync_wrapper

from zenml.artifact_stores import (
    BaseArtifactStore,
    BulkDeleteResult,
    ObjectDeleteFailure,
    ObjectInfo,
)
from zenml.integrations.s3.flavors.s3_artifact_store_flavor import (
    S3ArtifactStoreConfig,
)
from zenml.integrations.s3.utils import split_s3_path
from zenml.io.fileio import convert_to_str
from zenml.logger import get_logger
from zenml.secret.schemas import AWSSecretSchema
from zenml.stack.authentication_mixin import AuthenticationMixin
from zenml.utils import io_utils

logger = get_logger(__name__)

PathType = Union[bytes, str]
S3_DELETE_MAX_OBJECTS = 1000
DEFAULT_S3_DOWNLOAD_WORKERS = 8


def _normalize_s3_path(path: str) -> str:
    """Normalizes an S3 path by removing the protocol prefix if present.

    Args:
        path: The path to normalize.

    Returns:
        The normalized path.
    """
    if path.startswith("s3://"):
        return path[5:]
    return path


class ZenMLS3Filesystem(s3fs.S3FileSystem):  # type: ignore[misc]
    """Modified s3fs.S3FileSystem to disable caching.

    The original s3fs.S3FileSystem caches all class instances based on the
    constructor input arguments and it never releases them. This is problematic
    in the context of the ZenML server, because the server is a long-running
    process that instantiates many S3 filesystems with different credentials,
    especially when the credentials are generated by service connectors.

    The caching behavior of s3fs causes the server to slowly consume more and
    more memory over time until it crashes. This class disables the caching
    behavior of s3fs by setting the `cachable` attribute to `False`.

    In addition to disabling instance caching, this class also provides a
    correct cleanup implementation by overriding the `close_session` method
    the S3 aiobotocore client. The original one provided by s3fs was causing
    memory leaks by creating a new event loop in the destructor instead of
    using the existing one.

    A `close` method is also provided to allow for synchronous on-demand cleanup
    of the S3 client.
    """

    cachable = False

    @staticmethod
    async def _safe_aexit_s3_creator(s3_creator: Any) -> None:
        """Exit an aiobotocore client context manager, tolerating double-close.

        The s3fs finalizer and ZenML's explicit cleanup can both call
        ``__aexit__`` on the same creator object. The second call raises
        ``AssertionError("Session was never entered")`` in aiobotocore
        because ``http_session._sessions`` is already ``None``. This
        wrapper treats that specific assertion as a harmless no-op.

        Args:
            s3_creator: The aiobotocore async context manager to exit.

        Raises:
            AssertionError: If the assertion is unrelated to double-close.
        """
        try:
            await s3_creator.__aexit__(None, None, None)
        except AssertionError as exc:
            _MSG = "Session was never entered"
            if not (exc.args and _MSG in str(exc.args[0])):
                raise
            logger.debug(
                "Suppressed double-close of aiobotocore session: %s", exc
            )

    async def _close(self) -> None:
        """Close the S3 client."""
        if self._s3creator is not None:  # type: ignore[has-type]
            await self._safe_aexit_s3_creator(self._s3creator)  # type: ignore[has-type]
            self._s3creator = None
            self._s3 = None

    close = sync_wrapper(_close)

    @staticmethod
    def close_session(loop: Any, s3: Any) -> None:
        """Close the S3 client session.

        Args:
            loop: The event loop to use for closing the session.
            s3: The S3 client to close.
        """
        # IMPORTANT: This method is a copy of the original close_session method
        # from s3fs.S3FileSystem. The only difference is that it uses the
        # provided event loop instead of creating a new one, and routes
        # through _safe_aexit_s3_creator to tolerate double-close.
        if loop is not None and loop.is_running():
            try:
                # NOTE: this is the line in the original method that causes
                # the memory leak
                # loop = asyncio.get_event_loop()
                loop.create_task(ZenMLS3Filesystem._safe_aexit_s3_creator(s3))
                return
            except RuntimeError:
                pass
            try:
                sync(
                    loop,
                    ZenMLS3Filesystem._safe_aexit_s3_creator,
                    s3,
                    timeout=0.1,
                )
                return
            except FSTimeoutError:
                pass
        try:
            # close the actual socket
            s3._client._endpoint.http_session._connector._close()
        except AttributeError:
            # but during shutdown, it may have gone
            pass


class S3ArtifactStore(BaseArtifactStore, AuthenticationMixin):
    """Artifact Store for S3 based artifacts."""

    _filesystem: Optional[ZenMLS3Filesystem] = None
    _boto3_client_holder: Optional[Any] = None

    is_versioned: bool = False

    def __init__(
        self,
        *args: Any,
        **kwargs: Any,
    ) -> None:
        """Initializes the artifact store.

        Args:
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.
        """
        super().__init__(*args, **kwargs)
        self._boto3_bucket_holder = None
        self._boto3_client_holder = None

        # determine bucket versioning status
        versioning = self._boto3_bucket.Versioning()
        with self._shield_lack_of_versioning_permissions(
            "s3:GetBucketVersioning"
        ):
            if versioning.status == "Enabled":
                self.is_versioned = True
                logger.warning(
                    f"The artifact store bucket `{self.config.bucket}` is versioned, "
                    "this may slow down logging process significantly."
                )

    @property
    def config(self) -> S3ArtifactStoreConfig:
        """Get the config of this artifact store.

        Returns:
            The config of this artifact store.
        """
        return cast(S3ArtifactStoreConfig, self._config)

    def get_credentials(
        self,
    ) -> Tuple[Optional[str], Optional[str], Optional[str], Optional[str]]:
        """Gets authentication credentials.

        If an authentication secret is configured, the secret values are
        returned. Otherwise, we fall back to the plain text component
        attributes.

        Returns:
            Tuple (key, secret, token, region) of credentials used to
            authenticate with the S3 filesystem.

        Raises:
            RuntimeError: If the AWS connector behaves unexpectedly.
        """
        connector = self.get_connector()
        if connector:
            from botocore.client import BaseClient

            client = connector.connect()
            if not isinstance(client, BaseClient):
                raise RuntimeError(
                    f"Expected a botocore.client.BaseClient while trying to "
                    f"use the linked connector, but got {type(client)}."
                )
            credentials = client.credentials
            return (
                credentials.access_key,
                credentials.secret_key,
                credentials.token,
                client.meta.region_name,
            )

        secret = self.get_typed_authentication_secret(
            expected_schema_type=AWSSecretSchema
        )
        if secret:
            return (
                secret.aws_access_key_id,
                secret.aws_secret_access_key,
                secret.aws_session_token,
                None,
            )
        else:
            return self.config.key, self.config.secret, self.config.token, None

    @property
    def filesystem(self) -> ZenMLS3Filesystem:
        """The s3 filesystem to access this artifact store.

        Returns:
            The s3 filesystem.
        """
        # Refresh the credentials also if the connector has expired
        if self._filesystem and not self.connector_has_expired():
            return self._filesystem

        key, secret, token, region = self.get_credentials()

        # Use the region from the connector if available, otherwise some
        # remote workloads (e.g. Sagemaker) might not work correctly because
        # they look for the bucket in the wrong region
        client_kwargs = {}
        if region:
            client_kwargs["region_name"] = region
        if self.config.client_kwargs:
            client_kwargs.update(self.config.client_kwargs)

        self._filesystem = ZenMLS3Filesystem(
            key=key,
            secret=secret,
            token=token,
            client_kwargs=client_kwargs,
            config_kwargs=self.config.config_kwargs,
            s3_additional_kwargs=self.config.s3_additional_kwargs,
        )
        return self._filesystem

    def cleanup(self) -> None:
        """Close the filesystem."""
        if self._filesystem:
            self._filesystem.close()

    def open(self, path: PathType, mode: str = "r") -> Any:
        """Open a file at the given path.

        Args:
            path: Path of the file to open.
            mode: Mode in which to open the file. Currently, only
                'rb' and 'wb' to read and write binary files are supported.

        Returns:
            A file-like object.
        """
        return self.filesystem.open(path=path, mode=mode)

    def copyfile(
        self, src: PathType, dst: PathType, overwrite: bool = False
    ) -> None:
        """Copy a file.

        Args:
            src: The path to copy from.
            dst: The path to copy to.
            overwrite: If a file already exists at the destination, this
                method will overwrite it if overwrite=`True` and
                raise a FileExistsError otherwise.

        Raises:
            FileExistsError: If a file already exists at the destination
                and overwrite is not set to `True`.
        """
        if not overwrite and self.filesystem.exists(dst):
            raise FileExistsError(
                f"Unable to copy to destination '{convert_to_str(dst)}', "
                f"file already exists. Set `overwrite=True` to copy anyway."
            )

        # TODO [ENG-151]: Check if it works with overwrite=True or if we need to
        #  manually remove it first
        self.filesystem.copy(path1=src, path2=dst)

    def exists(self, path: PathType) -> bool:
        """Check whether a path exists.

        Args:
            path: The path to check.

        Returns:
            True if the path exists, False otherwise.
        """
        return self.filesystem.exists(path=path)  # type: ignore[no-any-return]

    def glob(self, pattern: PathType) -> List[PathType]:
        """Return all paths that match the given glob pattern.

        The glob pattern may include:
        - '*' to match any number of characters
        - '?' to match a single character
        - '[...]' to match one of the characters inside the brackets
        - '**' as the full name of a path component to match to search
            in subdirectories of any depth (e.g. '/some_dir/**/some_file)

        Args:
            pattern: The glob pattern to match, see details above.

        Returns:
            A list of paths that match the given glob pattern.
        """
        return [f"s3://{path}" for path in self.filesystem.glob(path=pattern)]

    def isdir(self, path: PathType) -> bool:
        """Check whether a path is a directory.

        Args:
            path: The path to check.

        Returns:
            True if the path is a directory, False otherwise.
        """
        return self.filesystem.isdir(path=path)  # type: ignore[no-any-return]

    def listdir(self, path: PathType) -> List[PathType]:
        """Return a list of files in a directory.

        Args:
            path: The path to list.

        Returns:
            A list of paths that are files in the given directory.
        """
        # remove s3 prefix if given, so we can remove the directory later as
        # this method is expected to only return filenames
        path = _normalize_s3_path(convert_to_str(path))

        def _extract_basename(file_dict: Dict[str, Any]) -> str:
            """Extracts the basename from a file info dict returned by the S3 filesystem.

            Args:
                file_dict: A file info dict returned by the S3 filesystem.

            Returns:
                The basename of the file.
            """
            file_path = cast(str, file_dict["Key"])
            base_name = file_path[len(path) :]
            return base_name.lstrip("/")

        return [
            _extract_basename(dict_)
            for dict_ in self.filesystem.listdir(path=path)
            # s3fs.listdir also returns the root directory, so we filter
            # it out here
            if _extract_basename(dict_)
        ]

    def makedirs(self, path: PathType) -> None:
        """Create a directory at the given path.

        If needed also create missing parent directories.

        Args:
            path: The path to create.
        """
        self.filesystem.makedirs(path=path, exist_ok=True)

    def mkdir(self, path: PathType) -> None:
        """Create a directory at the given path.

        Args:
            path: The path to create.
        """
        self.filesystem.makedir(path=path)

    def remove(self, path: PathType) -> None:
        """Remove the file at the given path.

        Args:
            path: The path of the file to remove.
        """
        self.filesystem.rm_file(path=path)

    def rename(
        self, src: PathType, dst: PathType, overwrite: bool = False
    ) -> None:
        """Rename source file to destination file.

        Args:
            src: The path of the file to rename.
            dst: The path to rename the source file to.
            overwrite: If a file already exists at the destination, this
                method will overwrite it if overwrite=`True` and
                raise a FileExistsError otherwise.

        Raises:
            FileExistsError: If a file already exists at the destination
                and overwrite is not set to `True`.
        """
        if not overwrite and self.filesystem.exists(dst):
            raise FileExistsError(
                f"Unable to rename file to '{convert_to_str(dst)}', "
                f"file already exists. Set `overwrite=True` to rename anyway."
            )

        # TODO [ENG-152]: Check if it works with overwrite=True or if we need
        #  to manually remove it first
        self.filesystem.rename(path1=src, path2=dst)

    def rmtree(self, path: PathType) -> None:
        """Remove the given directory.

        Args:
            path: The path of the directory to remove.
        """
        self.filesystem.delete(path=path, recursive=True)

    def stat(self, path: PathType) -> Dict[str, Any]:
        """Return stat info for the given path.

        Args:
            path: The path to get stat info for.

        Returns:
            A dictionary containing the stat info.
        """
        return self.filesystem.stat(path=path)  # type: ignore[no-any-return]

    def size(self, path: PathType) -> int:
        """Get the size of a file in bytes.

        Args:
            path: The path to the file.

        Returns:
            The size of the file in bytes.
        """
        return self.filesystem.size(path=path)  # type: ignore[no-any-return]

    def walk(
        self,
        top: PathType,
        topdown: bool = True,
        onerror: Optional[Callable[..., None]] = None,
    ) -> Iterable[Tuple[PathType, List[PathType], List[PathType]]]:
        """Return an iterator that walks the contents of the given directory.

        Args:
            top: Path of directory to walk.
            topdown: Unused argument to conform to interface.
            onerror: Unused argument to conform to interface.

        Yields:
            An Iterable of Tuples, each of which contain the path of the current
                directory path, a list of directories inside the current directory
                and a list of files inside the current directory.
        """
        # TODO [ENG-153]: Additional params
        for directory, subdirectories, files in self.filesystem.walk(path=top):
            yield f"s3://{directory}", subdirectories, files

    @staticmethod
    def _build_s3_uri(bucket_name: str, key: str) -> str:
        """Build an S3 URI from bucket and key parts."""
        if key:
            return f"s3://{bucket_name}/{key}"
        return f"s3://{bucket_name}"

    @staticmethod
    def _object_matches_prefix(key: str, prefix_key: str) -> bool:
        """Return whether an S3 object belongs to a requested prefix."""
        if not prefix_key:
            return True

        normalized_prefix = prefix_key.rstrip("/")
        return key == normalized_prefix or key.startswith(
            f"{normalized_prefix}/"
        )

    @staticmethod
    def _get_relative_key_path(key: str, prefix_key: str) -> str:
        """Get an S3 key path relative to a listed prefix."""
        normalized_prefix = prefix_key.rstrip("/")
        if not normalized_prefix:
            return key
        if key == normalized_prefix:
            return posixpath.basename(key)

        prefix_with_separator = f"{normalized_prefix}/"
        if key.startswith(prefix_with_separator):
            return key[len(prefix_with_separator) :]

        return posixpath.basename(key)

    @staticmethod
    def _get_safe_download_path(local_dir: str, relative_path: str) -> str:
        """Build a local download path that stays inside ``local_dir``."""
        normalized_relative_path = os.path.normpath(relative_path)
        if normalized_relative_path in ("", "."):
            raise ValueError("Object relative path cannot be empty.")
        if os.path.isabs(normalized_relative_path) or (
            normalized_relative_path == ".."
            or normalized_relative_path.startswith(f"..{os.sep}")
        ):
            raise ValueError(
                f"Object relative path `{relative_path}` escapes the local "
                "download directory."
            )

        destination = os.path.abspath(
            os.path.join(local_dir, normalized_relative_path)
        )
        local_dir_absolute = os.path.abspath(local_dir)
        if os.path.commonpath([local_dir_absolute, destination]) != local_dir_absolute:
            raise ValueError(
                f"Object relative path `{relative_path}` escapes the local "
                "download directory."
            )

        return destination

    @staticmethod
    def _chunked(
        items: Sequence[Dict[str, str]], chunk_size: int
    ) -> Iterable[Sequence[Dict[str, str]]]:
        """Yield fixed-size chunks from a sequence."""
        for index in range(0, len(items), chunk_size):
            yield items[index : index + chunk_size]

    def _get_object_info(
        self, object_data: Dict[str, Any], bucket_name: str, prefix_key: str
    ) -> ObjectInfo:
        """Build object metadata from a native S3 listing entry."""
        key = cast(str, object_data["Key"])
        return ObjectInfo(
            uri=self._build_s3_uri(bucket_name, key),
            relative_path=self._get_relative_key_path(key, prefix_key),
            size=object_data.get("Size"),
            etag=object_data.get("ETag"),
            last_modified=object_data.get("LastModified"),
        )

    def _delete_s3_object_identifiers(
        self,
        bucket_name: str,
        object_identifiers: Sequence[Dict[str, str]],
        capture_exceptions: bool = True,
    ) -> BulkDeleteResult:
        """Delete S3 objects or versions in provider-safe batches."""
        deleted_paths: List[str] = []
        failures: List[ObjectDeleteFailure] = []

        for batch in self._chunked(
            object_identifiers, S3_DELETE_MAX_OBJECTS
        ):
            try:
                response = self._boto3_client.delete_objects(
                    Bucket=bucket_name,
                    Delete={"Objects": list(batch), "Quiet": False},
                )
            except Exception as e:
                if not capture_exceptions:
                    raise
                failures.extend(
                    ObjectDeleteFailure(
                        path=self._build_s3_uri(bucket_name, object_["Key"]),
                        error=e,
                    )
                    for object_ in batch
                )
                continue

            failed_identifiers = set()
            for error_data in response.get("Errors", []):
                key = cast(str, error_data["Key"])
                version_id = error_data.get("VersionId")
                failed_identifiers.add((key, version_id))
                error = RuntimeError(
                    f"{error_data.get('Code', 'Unknown')}: "
                    f"{error_data.get('Message', 'S3 object deletion failed')}"
                )
                failures.append(
                    ObjectDeleteFailure(
                        path=self._build_s3_uri(bucket_name, key), error=error
                    )
                )

            deleted_objects = response.get("Deleted", [])
            if deleted_objects:
                deleted_paths.extend(
                    self._build_s3_uri(bucket_name, cast(str, object_["Key"]))
                    for object_ in deleted_objects
                )
                continue

            deleted_paths.extend(
                self._build_s3_uri(bucket_name, object_["Key"])
                for object_ in batch
                if (object_["Key"], object_.get("VersionId"))
                not in failed_identifiers
            )

        return BulkDeleteResult(
            deleted_paths=deleted_paths, failures=failures
        )

    def list_objects(
        self, prefix: PathType, recursive: bool = False
    ) -> Iterable[ObjectInfo]:
        """List S3 objects below a prefix with native object metadata."""
        sanitized_prefix = self._sanitize_path(prefix)
        bucket_name, prefix_key = split_s3_path(sanitized_prefix)
        listing_prefix = prefix_key.rstrip("/")
        objects: List[ObjectInfo] = []

        paginator = self._boto3_client.get_paginator("list_objects_v2")
        for page in paginator.paginate(
            Bucket=bucket_name, Prefix=listing_prefix
        ):
            for object_data in page.get("Contents", []):
                key = cast(str, object_data["Key"])
                if key.endswith("/"):
                    continue
                if not self._object_matches_prefix(key, prefix_key):
                    continue

                object_info = self._get_object_info(
                    object_data, bucket_name, prefix_key
                )
                if recursive or "/" not in object_info.relative_path.strip(
                    "/"
                ):
                    objects.append(object_info)

        return objects

    def delete_objects(self, paths: Iterable[PathType]) -> BulkDeleteResult:
        """Delete multiple S3 objects with native batch delete calls."""
        objects_by_bucket: Dict[str, List[Dict[str, str]]] = {}
        failures: List[ObjectDeleteFailure] = []

        for path in paths:
            sanitized_path = self._sanitize_path(path)
            try:
                bucket_name, key = split_s3_path(sanitized_path)
                if not key:
                    raise ValueError(
                        f"Cannot delete S3 bucket root `{sanitized_path}`."
                    )
            except Exception as e:
                failures.append(
                    ObjectDeleteFailure(path=sanitized_path, error=e)
                )
                continue

            objects_by_bucket.setdefault(bucket_name, []).append({"Key": key})

        deleted_paths: List[str] = []
        for bucket_name, object_identifiers in objects_by_bucket.items():
            result = self._delete_s3_object_identifiers(
                bucket_name=bucket_name,
                object_identifiers=object_identifiers,
            )
            deleted_paths.extend(result.deleted_paths)
            failures.extend(result.failures)

        return BulkDeleteResult(
            deleted_paths=deleted_paths, failures=failures
        )

    def read_range(
        self, path: PathType, offset: int, length: Optional[int] = None
    ) -> bytes:
        """Read a byte range from S3 using a native ranged GetObject call."""
        if offset < 0:
            raise ValueError("Range read offset must be non-negative.")
        if length is not None and length < 0:
            raise ValueError("Range read length must be non-negative.")
        if length == 0:
            return b""

        sanitized_path = self._sanitize_path(path)
        bucket_name, key = split_s3_path(sanitized_path)
        range_header = f"bytes={offset}-"
        if length is not None:
            range_header = f"bytes={offset}-{offset + length - 1}"

        response = self._boto3_client.get_object(
            Bucket=bucket_name,
            Key=key,
            Range=range_header,
        )
        body = response["Body"]
        try:
            return cast(bytes, body.read())
        finally:
            body.close()

    def download_objects_to_directory(
        self,
        objects: Iterable[ObjectInfo],
        local_dir: PathType,
        max_workers: Optional[int] = None,
    ) -> bool:
        """Download S3 objects into a local directory with boto3 transfers."""
        object_list = list(objects)
        local_directory = convert_to_str(local_dir)
        if io_utils.is_remote(local_directory):
            raise ValueError("Download directory must be a local path.")
        if max_workers is not None and max_workers < 1:
            raise ValueError("Download worker count must be positive.")

        os.makedirs(local_directory, exist_ok=True)
        transfer_config = TransferConfig(
            max_concurrency=max_workers or DEFAULT_S3_DOWNLOAD_WORKERS
        )

        def _download_object(object_info: ObjectInfo) -> None:
            sanitized_uri = self._sanitize_path(object_info.uri)
            bucket_name, key = split_s3_path(sanitized_uri)
            destination = self._get_safe_download_path(
                local_directory, object_info.relative_path
            )
            os.makedirs(os.path.dirname(destination), exist_ok=True)
            self._boto3_client.download_file(
                Bucket=bucket_name,
                Key=key,
                Filename=destination,
                Config=transfer_config,
            )

        worker_count = max_workers or min(
            DEFAULT_S3_DOWNLOAD_WORKERS, max(1, len(object_list))
        )
        with ThreadPoolExecutor(max_workers=worker_count) as executor:
            list(executor.map(_download_object, object_list))

        return True

    def _remove_previous_file_versions(self, path: PathType) -> None:
        """Keep only the latest file version in the given path.

        Method is useful for logs stored in versioned file systems
        like AWS S3.

        Args:
            path: The path to the file.
        """
        if not self.is_versioned:
            return

        if isinstance(path, bytes):
            path = path.decode()
        bucket_name, prefix = split_s3_path(path)
        object_identifiers: List[Dict[str, str]] = []

        with self._shield_lack_of_versioning_permissions(
            "s3:ListBucketVersions"
        ):
            paginator = self._boto3_client.get_paginator(
                "list_object_versions"
            )
            for page in paginator.paginate(Bucket=bucket_name, Prefix=prefix):
                for version_data in page.get("Versions", []):
                    if version_data.get("Key") != prefix:
                        continue
                    if not version_data.get("IsLatest", False):
                        object_identifiers.append(
                            {
                                "Key": cast(str, version_data["Key"]),
                                "VersionId": cast(
                                    str, version_data["VersionId"]
                                ),
                            }
                        )
                for marker_data in page.get("DeleteMarkers", []):
                    if marker_data.get("Key") != prefix:
                        continue
                    if not marker_data.get("IsLatest", False):
                        object_identifiers.append(
                            {
                                "Key": cast(str, marker_data["Key"]),
                                "VersionId": cast(str, marker_data["VersionId"]),
                            }
                        )

        if not object_identifiers:
            return

        with self._shield_lack_of_versioning_permissions(
            "s3:DeleteObjectVersion"
        ):
            result = self._delete_s3_object_identifiers(
                bucket_name=bucket_name,
                object_identifiers=object_identifiers,
                capture_exceptions=False,
            )
            if result.failures:
                logger.warning(
                    "Failed to remove %d previous S3 object versions for %s: %s",
                    len(result.failures),
                    path,
                    [failure.path for failure in result.failures],
                )

    def _build_boto3_kwargs(self) -> Dict[str, Any]:
        """Build boto3 kwargs by layering config overrides over connector credentials.

        Returns:
            A fresh dictionary of boto3 kwargs that callers can safely mutate.
        """
        key, secret, token, region = self.get_credentials()

        kwargs: Dict[str, Any] = (
            self.config.client_kwargs.copy()
            if self.config.client_kwargs
            else {}
        )

        if key is not None:
            kwargs["aws_access_key_id"] = key
        if secret is not None:
            kwargs["aws_secret_access_key"] = secret
        if token is not None:
            kwargs["aws_session_token"] = token
        if region is not None and "region_name" not in kwargs:
            kwargs["region_name"] = region
        if self.config.config_kwargs and "config" not in kwargs:
            kwargs["config"] = Config(**self.config.config_kwargs)

        return kwargs

    @property
    def _boto3_client(self) -> Any:
        """Get the boto3 S3 client."""
        if self._boto3_client_holder and not self.connector_has_expired():
            return self._boto3_client_holder

        self._boto3_client_holder = boto3.client(
            "s3", **self._build_boto3_kwargs()
        )
        return self._boto3_client_holder

    @property
    def _boto3_bucket(self) -> Any:
        """Get the boto3 bucket object.

        Returns:
            The boto3 bucket object.
        """
        if self._boto3_bucket_holder and not self.connector_has_expired():
            return self._boto3_bucket_holder

        s3 = boto3.resource("s3", **self._build_boto3_kwargs())
        self._boto3_bucket_holder = s3.Bucket(self.config.bucket)
        return self._boto3_bucket_holder

    @staticmethod
    def _is_missing_versioning_permission_error(
        error: ClientError, auth_missing: str
    ) -> bool:
        """Return whether an AWS error indicates missing version permissions."""
        error_data = error.response.get("Error", {})
        error_code = error_data.get("Code", "")
        error_message = str(error)
        if error_data.get("Message"):
            error_message = f"{error_message} {error_data['Message']}"
        error_message = error_message.lower()

        if error_code in {"AccessDenied", "UnauthorizedOperation"}:
            return True
        return (
            auth_missing.lower() in error_message
            and (
                "not authorized" in error_message
                or "access denied" in error_message
            )
        )

    @contextmanager
    def _shield_lack_of_versioning_permissions(
        self, auth_missing: str
    ) -> Generator[Any, None, None]:
        try:
            yield
        except ClientError as e:
            if self._is_missing_versioning_permission_error(e, auth_missing):
                logger.warning(
                    "Your AWS Connector is lacking critical Versioning permissions. "
                    f"Please check that `{auth_missing}` is granted."
                    "This is needed to remove previous versions of log files from your "
                    "Artifact Store bucket."
                )
                self.is_versioned = False
                return
            raise
