"""add vizualisations [0ede689b266a].

Revision ID: 0ede689b266a
Revises: 0.90.0
Create Date: 2025-10-15 23:48:54.468181

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ede689b266a"
down_revision = "0.90.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curated_visualization",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "artifact_version_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("visualization_index", sa.Integer(), nullable=False),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column(
            "layout_size", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("resource_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"],
            ["artifact_version.id"],
            name="fk_curated_visualization_artifact_version_id_artifact_version",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="fk_curated_visualization_project_id_project",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "artifact_version_id",
            "visualization_index",
            "resource_id",
            "resource_type",
            name="unique_curated_visualization_resource_link",
        ),
    )
    with op.batch_alter_table(
        "curated_visualization", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_curated_visualization_artifact_version_id_visualization_index",
            ["artifact_version_id", "visualization_index"],
            unique=False,
        )
        batch_op.create_index(
            "ix_curated_visualization_display_order",
            ["display_order"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "curated_visualization", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_curated_visualization_display_order")
        batch_op.drop_index(
            "ix_curated_visualization_artifact_version_id_visualization_index"
        )

    op.drop_table("curated_visualization")
    # ### end Alembic commands ###
