"""Rename project to workspace [1de87a8c8e8c].

Revision ID: 1de87a8c8e8c
Revises: 0.22.0
Create Date: 2022-11-24 14:08:56.377347

"""
from collections import defaultdict
from typing import Tuple, List, Dict

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de87a8c8e8c'
down_revision = '0.22.0'
branch_labels = None
depends_on = None


def _fk_constraint_name(source: str, target: str, source_column: str) -> str:
    """Defines the name of a foreign key constraint.

    See https://alembic.sqlalchemy.org/en/latest/batch.html#dropping-unnamed-or-named-foreign-key-constraints.

    Args:
        source: Source table name.
        target: Target table name.
        source_column: Source column name.

    Returns:
        Name of the foreign key constraint.
    """
    return f"fk_{source}_{source_column}_{target}"


def _drop_fk_constraint(source: str, constraint_name: str) -> None:
    """Drops a (potentially unnamed) foreign key constraint.

    This is somewhat tricky since we have not explicitly named constraints
    before and each backend names the constraints differently. SQLite even
    doesn't name them at all.

    See https://alembic.sqlalchemy.org/en/latest/batch.html#dropping-unnamed-or-named-foreign-key-constraints.

    Args:
        source: Source table name.
        constraint_name: Name of the foreign key constraint.
    """
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table(
        source, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint(
            constraint_name=constraint_name,
            type_="foreignkey",
        )


def _create_fk_constraint(
    source: str,
    target: str,
    source_column: str,
    target_column: str,
    ondelete: str,
) -> None:
    """Create a foreign key constraint.

    Args:
        source: Source table name.
        target: Target table name.
        source_column: Source column name.
        target_column: Target column name.
        ondelete: On delete behavior.
    """
    constraint_name = _fk_constraint_name(source, target, source_column)
    with op.batch_alter_table(source) as batch_op:
        batch_op.create_foreign_key(
            constraint_name=constraint_name,
            referent_table=target,
            local_cols=[source_column],
            remote_cols=[target_column],
            ondelete=ondelete,
        )


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""

    table_names: List[str] = [
        'flavor',
        'pipeline',
        'pipeline_run',
        'stack',
        'stack_component',
        'team_role_assignment',
        'user_role_assignment'
    ]

    new_fk_constraints: List[Tuple[str, str, str, str, str]] = [
        *[
            (source, "workspace", "workspace_id", "id", "CASCADE")
            for source in table_names
        ],
    ]
    old_fk_constraints = [
        *[
            (source, "workspace", "project_id", "id", "CASCADE")
            for source in table_names
        ],
    ]

    engine_name = op.get_bind().engine.name

    # Under MySQL, we need to sort the old foreign keys by source table and
    # source column first since the default foreign key names contain the
    # foreign key number.
    if engine_name == "mysql":
        old_fk_constraints.sort(key=lambda x: (x[0], x[2]))
    source_table_fk_constraint_counts: Dict[str, int] = defaultdict(int)

    # Drop old foreign key constraints.
    for source, target, source_column, _, _ in old_fk_constraints:
        if engine_name == "sqlite":
            constraint_name = _fk_constraint_name(source, target, source_column)
        elif engine_name == "mysql":
            source_table_fk_constraint_counts[source] += 1
            fk_num = source_table_fk_constraint_counts[source]
            constraint_name = f"{source}_ibfk_{fk_num}"
        else:
            raise NotImplementedError(f"Unsupported engine: {engine_name}")
        _drop_fk_constraint(source, constraint_name)

    # Rename columns
    for table in table_names:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.alter_column('project_id', new_column_name='workspace_id')

    # Create new foreign key constraints
    for (
            source,
            target,
            source_column,
            target_column,
            ondelete,
    ) in new_fk_constraints:
        _create_fk_constraint(
            source, target, source_column, target_column, ondelete
        )


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=True))
        batch_op.drop_constraint('fk_user_role_assignment_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_role_assignment_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('team_role_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=True))
        batch_op.drop_constraint('fk_team_role_assignment_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_role_assignment_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('stack_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_stack_component_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_stack_component_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_stack_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_stack_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_pipeline_run_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_pipeline_run_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_pipeline_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_pipeline_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('flavor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_flavor_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_flavor_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    # ### end Alembic commands ###
