"""extend_artifact_with_original_name [23c086a86a2b].

Revision ID: 23c086a86a2b
Revises: 0.70.0
Create Date: 2024-11-22 10:26:43.027089

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23c086a86a2b"
down_revision = "0.70.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifact", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("original_name", sa.TEXT(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifact", schema=None) as batch_op:
        batch_op.drop_column("original_name")

    # ### end Alembic commands ###
