"""Link pipeline runs to trigger executions [23e4cabea464].

Revision ID: 23e4cabea464
Revises: b677988b61e1
Create Date: 2024-02-13 12:55:18.257560

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "23e4cabea464"
down_revision = "b677988b61e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "trigger_execution_id",
                sqlmodel.sql.sqltypes.GUID(),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "fk_pipeline_run_trigger_execution_id_trigger_execution",
            "trigger_execution",
            ["trigger_execution_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_pipeline_run_trigger_execution_id_trigger_execution",
            type_="foreignkey",
        )
        batch_op.drop_column("trigger_execution_id")

    # ### end Alembic commands ###
