"""Step configuration unique constraint [3d7e39f3ac92].

Revision ID: 3d7e39f3ac92
Revises: 4111cb9ac010
Create Date: 2025-06-18 11:27:52.865586

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d7e39f3ac92"
down_revision = "4111cb9ac010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("step_configuration", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_step_name_for_deployment", ["deployment_id", "name"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("step_configuration", schema=None) as batch_op:
        batch_op.drop_constraint(
            "unique_step_name_for_deployment", type_="unique"
        )

    # ### end Alembic commands ###
