"""endpoint_artifact>deployment_artifact [4e1972485075].

Revision ID: 4e1972485075
Revises: 0.51.0
Create Date: 2023-12-12 10:51:44.177810

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1972485075'
down_revision = '0.51.0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions_artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deployment_artifact', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_endpoint_artifact')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions_artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_endpoint_artifact', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_deployment_artifact')

    # ### end Alembic commands ###
