"""Add pipeline run unique constraint [6917bce75069].

Revision ID: 6917bce75069
Revises: 0.47.0
Create Date: 2023-11-15 16:07:24.343126

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6917bce75069"
down_revision = "0.47.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_orchestrator_run_id_for_deployment_id",
            ["deployment_id", "orchestrator_run_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.drop_constraint(
            "unique_orchestrator_run_id_for_deployment_id", type_="unique"
        )

    # ### end Alembic commands ###
