"""adding labels to stacks [6d2ebf1a2017].

Revision ID: 6d2ebf1a2017
Revises: 0.60.0
Create Date: 2024-07-04 15:29:45.744811

"""

# revision identifiers, used by Alembic.
revision = "6d2ebf1a2017"
down_revision = "0.60.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
