"""unique users [72675226b2de].

Revision ID: 72675226b2de
Revises: 479103df60b6
Create Date: 2024-02-29 14:58:25.584731

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "72675226b2de"
down_revision = "479103df60b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name", "is_service_account"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
