"""Remove shared columns [7500f434b71c].

Revision ID: 7500f434b71c
Revises: 0.45.4
Create Date: 2023-10-16 15:15:34.865337

"""
import base64
from datetime import datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7500f434b71c"
down_revision = "0.45.5"
branch_labels = None
depends_on = None


def _rename_old_default_entities(table: sa.Table) -> None:
    """Include owner id in the name of default entities.

    Args:
        table: The table in which to rename the default entities.
    """
    connection = op.get_bind()

    query = sa.select(
        table.c.id,
        table.c.user_id,
    ).where(table.c.name == "default")

    res = connection.execute(query).fetchall()
    for id, owner_id in res:
        name = f"default-{owner_id}"

        connection.execute(
            sa.update(table).where(table.c.id == id).values(name=name)
        )


def resolve_duplicate_names() -> None:
    """Resolve duplicate names for shareable entities."""
    connection = op.get_bind()

    meta = sa.MetaData(bind=op.get_bind())
    meta.reflect(
        only=("stack", "stack_component", "service_connector", "workspace")
    )

    stack_table = sa.Table("stack", meta)
    stack_component_table = sa.Table("stack_component", meta)
    workspace_table = sa.Table("workspace", meta)

    _rename_old_default_entities(stack_table)
    _rename_old_default_entities(stack_component_table)

    workspace_query = sa.select(workspace_table.c.id)
    utcnow = datetime.utcnow()

    stack_components = []
    stacks = []
    for row in connection.execute(workspace_query).fetchall():
        workspace_id = row[0]
        artifact_store_id = str(uuid4()).replace("-", "")
        default_artifact_store = {
            "id": artifact_store_id,
            "workspace_id": workspace_id,
            "name": "default",
            "type": "artifact_store",
            "flavor": "local",
            "configuration": base64.b64encode("{}".encode("utf-8")),
            "is_shared": True,
            "created": utcnow,
            "updated": utcnow,
        }
        orchestrator_id = str(uuid4()).replace("-", "")
        default_orchestrator = {
            "id": orchestrator_id,
            "workspace_id": workspace_id,
            "name": "default",
            "type": "orchestrator",
            "flavor": "local",
            "configuration": base64.b64encode("{}".encode("utf-8")),
            "is_shared": True,
            "created": utcnow,
            "updated": utcnow,
        }

        default_stack = {
            "id": str(uuid4()).replace("-", ""),
            "workspace_id": workspace_id,
            "name": "default",
            "components": {
                "artifact_store": [artifact_store_id],
                "orchestrator": [orchestrator_id],
            },
            "is_shared": True,
            "created": utcnow,
            "updated": utcnow,
        }
        stack_components.append(default_artifact_store)
        stack_components.append(default_orchestrator)
        stacks.append(default_stack)

    op.bulk_insert(stack_component_table, rows=stack_components)
    op.bulk_insert(stack_table, rows=stacks)

    service_connector_table = sa.Table("service_connector", meta)
    query = sa.select(
        service_connector_table.c.id,
        service_connector_table.c.name,
        service_connector_table.c.user_id,
    )

    names = set()
    for id, name, user_id in connection.execute(query).fetchall():
        if name in names:
            name = f"{name}-{user_id}"
            # This will never happen, as we had a constraint on unique names
            # per user
            assert name not in names
            connection.execute(
                sa.update(service_connector_table)
                .where(service_connector_table.c.id == id)
                .values(name=name)
            )

        names.add(name)


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    resolve_duplicate_names()

    with op.batch_alter_table("service_connector", schema=None) as batch_op:
        batch_op.drop_column("is_shared")

    with op.batch_alter_table("stack", schema=None) as batch_op:
        batch_op.drop_column("is_shared")

    with op.batch_alter_table("stack_component", schema=None) as batch_op:
        batch_op.drop_column("is_shared")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stack_component", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_shared", sa.BOOLEAN(), nullable=False)
        )

    with op.batch_alter_table("stack", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_shared", sa.BOOLEAN(), nullable=False)
        )

    with op.batch_alter_table("service_connector", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_shared", sa.BOOLEAN(), nullable=False)
        )
    # ### end Alembic commands ###
