"""Add platform event extra cols [77c8a1f91ab4].

Revision ID: 77c8a1f91ab4
Revises: 0.94.1
Create Date: 2026-03-30 15:51:09.472631

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import VARCHAR

# revision identifiers, used by Alembic.
revision = "77c8a1f91ab4"
down_revision = "0.94.2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trigger", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source_entity",
                VARCHAR(255),
                default=None,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "target_events",
                sa.String(length=65535).with_variant(sa.TEXT(), "mysql"),
                nullable=True,
            )
        )
        batch_op.create_index(
            "ix_trigger_flavor_source_entity",
            ["flavor", "source_entity"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trigger", schema=None) as batch_op:
        batch_op.drop_index("ix_trigger_flavor_source_entity")
        batch_op.drop_column("target_events")
        batch_op.drop_column("source_entity")

    # ### end Alembic commands ###
