"""add pagination indexes for pipeline runs and snapshots [9210b7665982].

Revision ID: 9210b7665982
Revises: 0.94.6
Create Date: 2026-06-03 16:08:25.358801

"""

from zenml.zen_stores.migrations.utils import (
    create_index_if_missing,
    drop_index_if_exists,
)

# revision identifiers, used by Alembic.
revision = "9210b7665982"
down_revision = "0.94.6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index_if_exists(
        "api_transaction", "ix_api_transaction_completed_expired"
    )
    create_index_if_missing(
        "api_transaction",
        "ix_api_transaction_completed_expired_id",
        ["completed", "expired", "id"],
    )

    create_index_if_missing(
        "artifact_version",
        "ix_artifact_version_artifact_id_version_number",
        ["artifact_id", "version_number"],
    )

    create_index_if_missing(
        "pipeline_run",
        "ix_pipeline_run_project_id_created_id",
        ["project_id", "created", "id"],
    )

    drop_index_if_exists(
        "pipeline_snapshot",
        "ix_pipeline_snapshot_project_id_created_id_name",
    )
    create_index_if_missing(
        "pipeline_snapshot",
        "ix_pipeline_snapshot_project_id_created_id",
        ["project_id", "created", "id"],
    )
    create_index_if_missing(
        "pipeline_snapshot",
        "ix_pipeline_snapshot_project_id_name",
        ["project_id", "name"],
    )

    create_index_if_missing(
        "step_configuration",
        "ix_step_configuration_snapshot_id_name",
        ["snapshot_id", "name"],
    )
    create_index_if_missing(
        "step_configuration",
        "ix_step_configuration_step_run_id",
        ["step_run_id"],
    )

    # Matches slow hydrated step-run list queries:
    # WHERE project_id = ? AND pipeline_run_id = ? AND name IN (...)
    # ORDER BY created, id.
    create_index_if_missing(
        "step_run",
        "ix_step_run_project_id_pipeline_run_id_name_created_id",
        ["project_id", "pipeline_run_id", "name", "created", "id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index_if_exists(
        "step_run", "ix_step_run_project_id_pipeline_run_id_name_created_id"
    )

    drop_index_if_exists(
        "step_configuration", "ix_step_configuration_step_run_id"
    )
    drop_index_if_exists(
        "step_configuration", "ix_step_configuration_snapshot_id_name"
    )

    drop_index_if_exists(
        "pipeline_snapshot",
        "ix_pipeline_snapshot_project_id_name",
    )
    drop_index_if_exists(
        "pipeline_snapshot",
        "ix_pipeline_snapshot_project_id_created_id",
    )
    drop_index_if_exists(
        "pipeline_snapshot",
        "ix_pipeline_snapshot_project_id_created_id_name",
    )

    drop_index_if_exists(
        "pipeline_run", "ix_pipeline_run_project_id_created_id"
    )

    drop_index_if_exists(
        "artifact_version", "ix_artifact_version_artifact_id_version_number"
    )

    drop_index_if_exists(
        "api_transaction", "ix_api_transaction_completed_expired_id"
    )
    create_index_if_missing(
        "api_transaction",
        "ix_api_transaction_completed_expired",
        ["completed", "expired"],
    )

    # ### end Alembic commands ###
