"""Rename project to workspace [afc72b8457d9].

Revision ID: afc72b8457d9
Revises: 0.22.0
Create Date: 2022-11-22 17:29:04.109273

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc72b8457d9'
down_revision = '0.22.0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_run_artifact',
    sa.Column('step_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('artifact_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name='fk_step_run_artifact_artifact_id_artifacts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step_run.id'], name='fk_step_run_artifact_step_id_step_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'artifact_id')
    )
    op.drop_table('step_run_input_artifact')
    with op.batch_alter_table('flavor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
        batch_op.drop_constraint('fk_flavor_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_flavor_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
        batch_op.drop_constraint('fk_pipeline_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_pipeline_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
        batch_op.drop_constraint('fk_pipeline_run_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_pipeline_run_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
        batch_op.drop_constraint('fk_stack_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_stack_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('stack_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
        batch_op.drop_constraint('fk_stack_component_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_stack_component_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('team_role_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
        batch_op.drop_constraint('fk_team_role_assignment_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_role_assignment_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
        batch_op.drop_constraint('fk_user_role_assignment_project_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_role_assignment_workspace_id_workspace', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user_role_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=True))
        batch_op.drop_constraint('fk_user_role_assignment_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_role_assignment_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('team_role_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=True))
        batch_op.drop_constraint('fk_team_role_assignment_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_team_role_assignment_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('stack_component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_stack_component_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_stack_component_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_stack_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_stack_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('pipeline_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_pipeline_run_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_pipeline_run_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_pipeline_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_pipeline_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('flavor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint('fk_flavor_workspace_id_workspace', type_='foreignkey')
        batch_op.create_foreign_key('fk_flavor_project_id_workspace', 'workspace', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workspace_id')

    op.create_table('step_run_input_artifact',
    sa.Column('step_id', sa.CHAR(length=32), nullable=False),
    sa.Column('artifact_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name='fk_step_run_input_artifact_artifact_id_artifacts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step_run.id'], name='fk_step_run_input_artifact_step_id_step_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'artifact_id')
    )
    op.drop_table('step_run_artifact')
    # ### end Alembic commands ###
