"""Add unique constraint [b6ef2971e7a6].

Revision ID: b6ef2971e7a6
Revises: 0.46.1
Create Date: 2023-11-13 20:52:10.384274

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6ef2971e7a6"
down_revision = "0.46.1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_orchestrator_run_id",
            ["orchestrator_run_id", "deployment_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.drop_constraint("unique_orchestrator_run_id", type_="unique")

    # ### end Alembic commands ###
