"""Increase length on flavor config schema

Revision ID: c1b18cec3a48
Revises: a8c6cd6b3f34
Create Date: 2022-10-19 17:12:19.481776

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b18cec3a48'
down_revision = 'a8c6cd6b3f34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavorschema', schema=None) as batch_op:
        batch_op.alter_column('config_schema',
                              existing_type=sa.VARCHAR(),
                              type_=sa.String(4096),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flavorschema', schema=None) as batch_op:
        batch_op.alter_column('config_schema',
                              existing_type=sa.VARCHAR(),
                              type_=sa.String(),
                              nullable=False)

    # ### end Alembic commands ###
