"""add flavor resource id attr [cfb5b7e227bc].

Revision ID: cfb5b7e227bc
Revises: 0b06faa59c93
Create Date: 2023-05-08 23:23:15.292743

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfb5b7e227bc"
down_revision = "0b06faa59c93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flavor", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "connector_resource_id_attr",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flavor", schema=None) as batch_op:
        batch_op.drop_column("connector_resource_id_attr")

    # ### end Alembic commands ###
