"""fixed migration second iteration [d40acc2961ca].

Revision ID: d40acc2961ca
Revises: 7f603e583dd7
Create Date: 2023-10-13 16:51:06.557937

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.engine.base import Connection

# revision identifiers, used by Alembic.
revision = "d40acc2961ca"
down_revision = "7f603e583dd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind: Connection = op.get_bind()
    column_info = sa.inspect(bind).get_columns("pipeline_run")
    columns = [c["name"] for c in column_info]

    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        if "pipeline_configuration" not in columns:
            batch_op.add_column(
                sa.Column("pipeline_configuration", sa.TEXT(), nullable=True)
            )

        if "client_environment" not in columns:
            batch_op.add_column(
                sa.Column("client_environment", sa.TEXT(), nullable=True)
            )

        if "stack_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "stack_id", sqlmodel.sql.sqltypes.GUID(), nullable=True
                )
            )
            batch_op.create_foreign_key(
                "fk_pipeline_run_stack_id_stack",
                "stack",
                ["stack_id"],
                ["id"],
                ondelete="SET NULL",
            )

        if "build_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "build_id", sqlmodel.sql.sqltypes.GUID(), nullable=True
                )
            )
            batch_op.create_foreign_key(
                "fk_pipeline_run_build_id_pipeline_build",
                "pipeline_build",
                ["build_id"],
                ["id"],
                ondelete="SET NULL",
            )

        if "schedule_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "schedule_id", sqlmodel.sql.sqltypes.GUID(), nullable=True
                )
            )
            batch_op.create_foreign_key(
                "fk_pipeline_run_schedule_id_schedule",
                "schedule",
                ["schedule_id"],
                ["id"],
                ondelete="SET NULL",
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
    #     batch_op.drop_constraint(
    #         "fk_pipeline_run_schedule_id_schedule", type_="foreignkey"
    #     )
    #     batch_op.drop_constraint(
    #         "fk_pipeline_run_stack_id_stack", type_="foreignkey"
    #     )
    #     batch_op.drop_constraint(
    #         "fk_pipeline_run_build_id_pipeline_build", type_="foreignkey"
    #     )
    #     batch_op.drop_column("schedule_id")
    #     batch_op.drop_column("build_id")
    #     batch_op.drop_column("stack_id")
    #     batch_op.drop_column("client_environment")
    #     batch_op.drop_column("pipeline_configuration")

    # ### end Alembic commands ###
