#  Copyright (c) ZenML GmbH 2026. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied. See the License for the specific language governing
#  permissions and limitations under the License.
"""Helpers for dynamic pipeline output validation and normalization."""

from typing import Any, Callable, Dict, List
from uuid import UUID

from zenml.models import ArtifactVersionResponse
from zenml.steps.utils import (
    SINGLE_RETURN_OUT_NAME,
    parse_return_type_annotations,
)


def _to_plain_artifact_version(
    artifact: ArtifactVersionResponse,
) -> ArtifactVersionResponse:
    """Convert pipeline outputs to plain artifact response models.

    Dynamic step outputs are represented as `OutputArtifact` instances, but
    pipeline boundaries should only expose generic artifact responses so parent
    step compilation does not interpret child outputs as in-run step outputs.

    Args:
        artifact: The artifact response returned by a dynamic pipeline.

    Returns:
        A plain `ArtifactVersionResponse`.
    """
    if type(artifact) is ArtifactVersionResponse:
        return artifact

    # Convert subclasses to plain artifact versions
    return ArtifactVersionResponse.model_validate(artifact.model_dump())


def validate_pipeline_outputs(
    value: Any,
) -> List[ArtifactVersionResponse]:
    """Validate a child pipeline return value.

    Args:
        value: The pipeline return value.

    Raises:
        ValueError: If outputs are not valid.

    Returns:
        A list of artifact responses.
    """
    error_message = (
        "Only artifacts (or tuples of artifacts) are currently supported as "
        "pipeline outputs. Please return artifacts generated by steps or "
        "manually store your data as an artifact. Got "
        f"{type(value).__name__}."
    )

    if value is None:
        artifacts = []
    elif isinstance(value, ArtifactVersionResponse):
        artifacts = [value]
    elif isinstance(value, dict):
        raise ValueError(error_message)
    elif isinstance(value, tuple):
        if not all(
            isinstance(item, ArtifactVersionResponse) for item in value
        ):
            raise ValueError(error_message)
        artifacts = list(value)
    else:
        raise ValueError(error_message)

    return [_to_plain_artifact_version(artifact) for artifact in artifacts]


def get_pipeline_entrypoint_output_names(
    pipeline_entrypoint: Callable[..., Any],
) -> List[str]:
    """Output names from the entrypoint's return-type annotation.

    Returns the
    Empty if the entrypoint has no annotated returns.

    Args:
        pipeline_entrypoint: The dynamic pipeline entrypoint function.

    Returns:
        Output names from the entrypoint annotation.
    """
    return list(parse_return_type_annotations(pipeline_entrypoint).keys())


def resolve_pipeline_output_names(
    declared_names: List[str], count: int
) -> List[str]:
    """Resolve effective output names for persisted dynamic pipeline outputs.

    Used by both server-side persistence and client-side `PipelineFuture` so
    that the names always agree. Falls back to `SINGLE_RETURN_OUT_NAME` for a
    single unnamed output and `output_0`, `output_1`, ... for unnamed
    multi-output pipelines.

    Args:
        declared_names: Output names declared on the pipeline entrypoint, if
            any.
        count: Number of output artifacts actually produced.

    Returns:
        Output names in deterministic order.
    """
    if count == 0:
        return []

    if count == 1:
        if declared_names:
            return [declared_names[0]]
        return [SINGLE_RETURN_OUT_NAME]

    if len(declared_names) == count:
        return declared_names

    return [f"output_{i}" for i in range(count)]


def prepare_pipeline_output_artifacts(
    value: Any,
    pipeline_entrypoint: Callable[..., Any],
) -> Dict[str, UUID]:
    """Build the output ID payload for a pipeline run status update.

    Args:
        value: The dynamic pipeline return value.
        pipeline_entrypoint: Dynamic pipeline entrypoint for output naming.

    Returns:
        Output artifact version IDs keyed by effective output name.
    """
    artifacts = validate_pipeline_outputs(value=value)
    output_names = resolve_pipeline_output_names(
        declared_names=get_pipeline_entrypoint_output_names(
            pipeline_entrypoint
        ),
        count=len(artifacts),
    )

    return {
        output_name: artifact.id
        for output_name, artifact in zip(output_names, artifacts)
    }
