#  Copyright (c) ZenML GmbH 2023. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#       https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  or implied. See the License for the specific language governing
#  permissions and limitations under the License.
"""Pydantic models for the various concepts in ZenML."""

# ------------------------------------- V2 -------------------------------------

# V2 Base
from zenml.models.v2.base.base import (
    BaseDatedResponseBody,
    BaseIdentifiedResponse,
    BaseRequest,
    BaseResponse,
    BaseResponseBody,
    BaseResponseMetadata,
    BaseResponseResources,
    BaseUpdate,
    BaseZenModel,
)
from zenml.models.v2.base.filter import (
    BaseFilter,
    BoolFilter,
    NumericFilter,
    StrFilter,
    UUIDFilter,
)
from zenml.models.v2.base.page import Page
from zenml.models.v2.base.scoped import (
    ProjectScopedFilter,
    ProjectScopedRequest,
    ProjectScopedResponse,
    ProjectScopedResponseBody,
    ProjectScopedResponseMetadata,
    ProjectScopedResponseResources,
    RunMetadataFilterMixin,
    TaggableFilter,
    UserScopedFilter,
    UserScopedRequest,
    UserScopedResponse,
    UserScopedResponseBody,
    UserScopedResponseMetadata,
)

# V2 Core
from zenml.models.v2.core.api_key import (
    APIKey,
    APIKeyFilter,
    APIKeyInternalResponse,
    APIKeyInternalUpdate,
    APIKeyRequest,
    APIKeyResponse,
    APIKeyResponseBody,
    APIKeyResponseMetadata,
    APIKeyRotateRequest,
    APIKeyUpdate,
)
from zenml.models.v2.core.api_transaction import (
    ApiTransactionRequest,
    ApiTransactionResponse,
    ApiTransactionResponseBody,
    ApiTransactionResponseMetadata,
    ApiTransactionResponseResources,
    ApiTransactionUpdate,
)
from zenml.models.v2.core.artifact import (
    ArtifactFilter,
    ArtifactRequest,
    ArtifactResponse,
    ArtifactResponseBody,
    ArtifactResponseMetadata,
    ArtifactResponseResources,
    ArtifactUpdate,
)
from zenml.models.v2.core.artifact_version import (
    ArtifactVersionFilter,
    ArtifactVersionRequest,
    ArtifactVersionResponse,
    ArtifactVersionResponseBody,
    ArtifactVersionResponseMetadata,
    ArtifactVersionResponseResources,
    ArtifactVersionUpdate,
    LazyArtifactVersionResponse,
)
from zenml.models.v2.core.artifact_visualization import (
    ArtifactVisualizationRequest,
    ArtifactVisualizationResponse,
    ArtifactVisualizationResponseBody,
    ArtifactVisualizationResponseMetadata,
    ArtifactVisualizationResponseResources,
)
from zenml.models.v2.core.code_reference import (
    CodeReferenceRequest,
    CodeReferenceResponse,
    CodeReferenceResponseBody,
    CodeReferenceResponseMetadata,
)
from zenml.models.v2.core.code_repository import (
    CodeRepositoryFilter,
    CodeRepositoryRequest,
    CodeRepositoryResponse,
    CodeRepositoryResponseBody,
    CodeRepositoryResponseMetadata,
    CodeRepositoryResponseResources,
    CodeRepositoryUpdate,
)
from zenml.models.v2.core.component import (
    ComponentBase,
    ComponentFilter,
    ComponentRequest,
    ComponentResponse,
    ComponentResponseBody,
    ComponentResponseMetadata,
    ComponentResponseResources,
    ComponentUpdate,
    DefaultComponentRequest,
)
from zenml.models.v2.core.curated_visualization import (
    CuratedVisualizationRequest,
    CuratedVisualizationResponse,
    CuratedVisualizationResponseBody,
    CuratedVisualizationResponseMetadata,
    CuratedVisualizationResponseResources,
    CuratedVisualizationUpdate,
)
from zenml.models.v2.core.deployment import (
    DeploymentFilter,
    DeploymentOperationalState,
    DeploymentRequest,
    DeploymentResponse,
    DeploymentResponseBody,
    DeploymentResponseMetadata,
    DeploymentResponseResources,
    DeploymentUpdate,
)
from zenml.models.v2.core.device import (
    OAuthDeviceFilter,
    OAuthDeviceInternalRequest,
    OAuthDeviceInternalResponse,
    OAuthDeviceInternalUpdate,
    OAuthDeviceResponse,
    OAuthDeviceResponseBody,
    OAuthDeviceResponseMetadata,
    OAuthDeviceResponseResources,
    OAuthDeviceUpdate,
)
from zenml.models.v2.core.flavor import (
    FlavorFilter,
    FlavorRequest,
    FlavorResponse,
    FlavorResponseBody,
    FlavorResponseMetadata,
    FlavorResponseResources,
    FlavorUpdate,
)
from zenml.models.v2.core.hook_invocation import (
    HookInvocationFilter,
    HookInvocationRequest,
    HookInvocationResponse,
    HookInvocationResponseBody,
    HookInvocationResponseMetadata,
    HookInvocationResponseResources,
)
from zenml.models.v2.core.logs import (
    LogsRequest,
    LogsResponse,
    LogsResponseBody,
    LogsResponseMetadata,
    LogsResponseResources,
    LogsUpdate,
)
from zenml.models.v2.core.model import (
    ModelFilter,
    ModelRequest,
    ModelResponse,
    ModelResponseBody,
    ModelResponseMetadata,
    ModelResponseResources,
    ModelUpdate,
)
from zenml.models.v2.core.model_version import (
    ModelVersionFilter,
    ModelVersionRequest,
    ModelVersionResponse,
    ModelVersionResponseBody,
    ModelVersionResponseMetadata,
    ModelVersionResponseResources,
    ModelVersionUpdate,
)
from zenml.models.v2.core.model_version_artifact import (
    ModelVersionArtifactFilter,
    ModelVersionArtifactRequest,
    ModelVersionArtifactResponse,
    ModelVersionArtifactResponseBody,
)
from zenml.models.v2.core.model_version_pipeline_run import (
    ModelVersionPipelineRunFilter,
    ModelVersionPipelineRunRequest,
    ModelVersionPipelineRunResponse,
    ModelVersionPipelineRunResponseBody,
)
from zenml.models.v2.core.pipeline import (
    PipelineFilter,
    PipelineRequest,
    PipelineResponse,
    PipelineResponseBody,
    PipelineResponseMetadata,
    PipelineResponseResources,
    PipelineUpdate,
)
from zenml.models.v2.core.pipeline_build import (
    PipelineBuildBase,
    PipelineBuildFilter,
    PipelineBuildRequest,
    PipelineBuildResponse,
    PipelineBuildResponseBody,
    PipelineBuildResponseMetadata,
    PipelineBuildResponseResources,
)
from zenml.models.v2.core.pipeline_run import (
    PipelineRunFilter,
    PipelineRunRequest,
    PipelineRunResponse,
    PipelineRunResponseBody,
    PipelineRunResponseMetadata,
    PipelineRunResponseResources,
    PipelineRunTriggerInfo,
    PipelineRunUpdate,
)
from zenml.models.v2.core.pipeline_snapshot import (
    PipelineSnapshotBase,
    PipelineSnapshotFilter,
    PipelineSnapshotRequest,
    PipelineSnapshotResponse,
    PipelineSnapshotResponseBody,
    PipelineSnapshotResponseMetadata,
    PipelineSnapshotResponseResources,
    PipelineSnapshotRunRequest,
    PipelineSnapshotUpdate,
)
from zenml.models.v2.core.project import (
    ProjectFilter,
    ProjectRequest,
    ProjectResponse,
    ProjectResponseBody,
    ProjectResponseMetadata,
    ProjectUpdate,
)
from zenml.models.v2.core.resource_pool import (
    ResourcePoolAllocation,
    ResourcePoolFilter,
    ResourcePoolQueueItem,
    ResourcePoolRequest,
    ResourcePoolResponse,
    ResourcePoolResponseBody,
    ResourcePoolResponseMetadata,
    ResourcePoolResponseResources,
    ResourcePoolUpdate,
)
from zenml.models.v2.core.resource_pool_subject_policy import (
    ResourcePoolSubjectPolicyFilter,
    ResourcePoolSubjectPolicyRequest,
    ResourcePoolSubjectPolicyResponse,
    ResourcePoolSubjectPolicyResponseBody,
    ResourcePoolSubjectPolicyResponseMetadata,
    ResourcePoolSubjectPolicyResponseResources,
    ResourcePoolSubjectPolicyUpdate,
)
from zenml.models.v2.core.resource_request import (
    ResourceRequestFilter,
    ResourceRequestRequest,
    ResourceRequestResponse,
    ResourceRequestResponseBody,
    ResourceRequestResponseMetadata,
    ResourceRequestResponseResources,
)
from zenml.models.v2.core.run_metadata import (
    RunMetadataRequest,
)
from zenml.models.v2.core.run_template import (
    RunTemplateFilter,
    RunTemplateRequest,
    RunTemplateResponse,
    RunTemplateResponseBody,
    RunTemplateResponseMetadata,
    RunTemplateResponseResources,
    RunTemplateUpdate,
)
from zenml.models.v2.core.run_wait_condition import (
    RunWaitConditionFilter,
    RunWaitConditionLeaseUpdate,
    RunWaitConditionRequest,
    RunWaitConditionResolveRequest,
    RunWaitConditionResponse,
    RunWaitConditionResponseBody,
    RunWaitConditionResponseMetadata,
    RunWaitConditionResponseResources,
)
from zenml.models.v2.core.schedule import (
    ScheduleFilter,
    ScheduleRequest,
    ScheduleResponse,
    ScheduleResponseBody,
    ScheduleResponseMetadata,
    ScheduleResponseResources,
    ScheduleUpdate,
)
from zenml.models.v2.core.secret import (
    SecretFilter,
    SecretRequest,
    SecretResponse,
    SecretResponseBody,
    SecretResponseMetadata,
    SecretResponseResources,
    SecretUpdate,
)
from zenml.models.v2.core.server_settings import (
    ServerActivationRequest,
    ServerSettingsResponse,
    ServerSettingsResponseBody,
    ServerSettingsResponseMetadata,
    ServerSettingsResponseResources,
    ServerSettingsUpdate,
)
from zenml.models.v2.core.service import (
    ServiceFilter,
    ServiceRequest,
    ServiceResponse,
    ServiceResponseBody,
    ServiceResponseMetadata,
    ServiceResponseResources,
    ServiceUpdate,
)
from zenml.models.v2.core.service_account import (
    ServiceAccountFilter,
    ServiceAccountInternalRequest,
    ServiceAccountInternalUpdate,
    ServiceAccountRequest,
    ServiceAccountResponse,
    ServiceAccountResponseBody,
    ServiceAccountResponseMetadata,
    ServiceAccountUpdate,
)
from zenml.models.v2.core.service_connector import (
    ServiceConnectorConfiguration,
    ServiceConnectorFilter,
    ServiceConnectorRequest,
    ServiceConnectorResponse,
    ServiceConnectorResponseBody,
    ServiceConnectorResponseMetadata,
    ServiceConnectorResponseResources,
    ServiceConnectorUpdate,
)
from zenml.models.v2.core.stack import (
    DefaultStackRequest,
    StackFilter,
    StackRequest,
    StackResponse,
    StackResponseBody,
    StackResponseMetadata,
    StackResponseResources,
    StackUpdate,
)
from zenml.models.v2.core.step_run import (
    StepHeartbeatResponse,
    StepRunFilter,
    StepRunRequest,
    StepRunResponse,
    StepRunResponseBody,
    StepRunResponseMetadata,
    StepRunResponseResources,
    StepRunUpdate,
)
from zenml.models.v2.core.stream_event import (
    StreamEvent,
    StreamBatchRequest,
    StreamBatchResponse,
)
from zenml.models.v2.core.tag import (
    TagFilter,
    TagRequest,
    TagResponse,
    TagResponseBody,
    TagResponseMetadata,
    TagResponseResources,
    TagUpdate,
)
from zenml.models.v2.core.tag_resource import (
    TagResourceRequest,
    TagResourceResponse,
    TagResourceResponseBody,
)
from zenml.models.v2.core.triggers import (
    TRIGGER_CREATE_TYPE_UNION,
    TRIGGER_RETURN_TYPE_UNION,
    TRIGGER_UPDATE_TYPE_UNION,
    PlatformEventTrigger,
    PlatformEventTriggerRequest,
    PlatformEventTriggerResponse,
    PlatformEventTriggerResponseBody,
    PlatformEventTriggerUpdate,
    ScheduleTriggerRequest,
    ScheduleTriggerResponse,
    ScheduleTriggerResponseBody,
    ScheduleTriggerUpdate,
    SourceEntity,
    TriggerDispatchErrorSeverity,
    TriggerDispatchStatusCode,
    TriggerExecutionInfo,
    TriggerFilter,
    TriggerRequest,
    TriggerResponseBody,
    TriggerResponseMetadata,
    TriggerResponseResources,
    TriggerSnapshotDispatchState,
    TriggerUpdate,
)
from zenml.models.v2.core.user import (
    UserFilter,
    UserRequest,
    UserResponse,
    UserResponseBody,
    UserResponseMetadata,
    UserUpdate,
)
from zenml.models.v2.misc.auth_models import (
    OAuthDeviceAuthorizationRequest,
    OAuthDeviceAuthorizationResponse,
    OAuthDeviceTokenRequest,
    OAuthDeviceUserAgentHeader,
    OAuthDeviceVerificationRequest,
    OAuthRedirectResponse,
    OAuthTokenResponse,
)
from zenml.models.v2.misc.build_item import BuildItem
from zenml.models.v2.misc.exception_info import ExceptionInfo
from zenml.models.v2.misc.external_user import ExternalUserModel
from zenml.models.v2.misc.info_models import (
    ComponentInfo,
    ResourcesInfo,
    ServiceConnectorInfo,
    ServiceConnectorResourcesInfo,
)
from zenml.models.v2.misc.loaded_visualization import LoadedVisualization
from zenml.models.v2.misc.param_groups import (
    ArtifactVersionIdentifier,
    ModelVersionIdentifier,
    PipelineRunIdentifier,
    StepRunIdentifier,
)
from zenml.models.v2.misc.pipeline_run_dag import PipelineRunDAG
from zenml.models.v2.misc.run_metadata import (
    RunMetadataEntry,
    RunMetadataResource,
)
from zenml.models.v2.misc.run_statistics import (
    MetadataGrouping,
    MetadataMetric,
    RunStatisticsGroup,
    RunStatisticsRequest,
    RunStatisticsResponse,
    SimpleGrouping,
    SimpleMetric,
    StatisticsAggregation,
    StatisticsGrouping,
    StatisticsGroupingType,
    StatisticsMetric,
    StatisticsMetricSource,
    StatisticsTimeGranularity,
    TimeGrouping,
)
from zenml.models.v2.misc.server_models import (
    ServerDatabaseType,
    ServerDeploymentType,
    ServerLoadInfo,
    ServerModel,
)
from zenml.models.v2.misc.service import ServiceType

# V2 Misc
from zenml.models.v2.misc.service_connector_type import (
    AuthenticationMethodModel,
    ResourceTypeModel,
    ServiceConnectorRequirements,
    ServiceConnectorResourcesModel,
    ServiceConnectorTypedResourcesModel,
    ServiceConnectorTypeModel,
)
from zenml.models.v2.misc.stack_deployment import (
    DeployedStack,
    StackDeploymentConfig,
    StackDeploymentInfo,
)
from zenml.models.v2.misc.statistics import (
    ProjectStatistics,
    ServerStatistics,
)
from zenml.models.v2.misc.tag import (
    TagResource,
)
from zenml.models.v2.misc.user_auth import UserAuthModel

# ----------------------------- Forward References -----------------------------

# V2
APIKeyResponseBody.model_rebuild()
ApiTransactionResponse.model_rebuild()
ArtifactResponse.model_rebuild()
ArtifactResponseBody.model_rebuild()
ArtifactResponseMetadata.model_rebuild()
ArtifactResponseResources.model_rebuild()
ArtifactVersionRequest.model_rebuild()
ArtifactVersionResponseBody.model_rebuild()
ArtifactVersionResponseMetadata.model_rebuild()
ArtifactVersionResponseResources.model_rebuild()
ArtifactVisualizationResponse.model_rebuild()
ArtifactVisualizationResponseBody.model_rebuild()
ArtifactVisualizationResponseMetadata.model_rebuild()
ArtifactVisualizationResponseResources.model_rebuild()
CodeReferenceResponseBody.model_rebuild()
CodeRepositoryResponseBody.model_rebuild()
CodeRepositoryResponseMetadata.model_rebuild()
CodeRepositoryResponseResources.model_rebuild()
ComponentResponseBody.model_rebuild()
ComponentResponseMetadata.model_rebuild()
ComponentResponseResources.model_rebuild()
DeploymentRequest.model_rebuild()
DeploymentResponseBody.model_rebuild()
DeploymentResponseMetadata.model_rebuild()
DeploymentResponseResources.model_rebuild()
CuratedVisualizationResponseBody.model_rebuild()
CuratedVisualizationResponseMetadata.model_rebuild()
CuratedVisualizationResponseResources.model_rebuild()
CuratedVisualizationResponse.model_rebuild()
FlavorResponseBody.model_rebuild()
FlavorResponseMetadata.model_rebuild()
FlavorResponseResources.model_rebuild()
HookInvocationRequest.model_rebuild()
HookInvocationResponseBody.model_rebuild()
HookInvocationResponseMetadata.model_rebuild()
HookInvocationResponseResources.model_rebuild()
LogsRequest.model_rebuild()
LogsUpdate.model_rebuild()
LogsResponseResources.model_rebuild()
LogsResponseBody.model_rebuild()
LogsResponseMetadata.model_rebuild()
LazyArtifactVersionResponse.model_rebuild()
ModelResponseBody.model_rebuild()
ModelResponseMetadata.model_rebuild()
ModelResponseResources.model_rebuild()
ModelVersionResponseBody.model_rebuild()
ModelVersionResponseMetadata.model_rebuild()
ModelVersionResponseResources.model_rebuild()
ModelVersionArtifactResponseBody.model_rebuild()
ModelVersionPipelineRunResponseBody.model_rebuild()
OAuthDeviceResponseResources.model_rebuild()
PipelineResponseBody.model_rebuild()
PipelineResponseMetadata.model_rebuild()
PipelineResponseResources.model_rebuild()
PipelineBuildBase.model_rebuild()
PipelineBuildResponseBody.model_rebuild()
PipelineBuildResponseMetadata.model_rebuild()
PipelineBuildResponseResources.model_rebuild()
PipelineSnapshotRequest.model_rebuild()
PipelineSnapshotResponseBody.model_rebuild()
PipelineSnapshotResponseMetadata.model_rebuild()
PipelineSnapshotResponseResources.model_rebuild()
PipelineRunRequest.model_rebuild()
PipelineRunResponseBody.model_rebuild()
PipelineRunResponseMetadata.model_rebuild()
PipelineRunResponseResources.model_rebuild()
RunWaitConditionRequest.model_rebuild()
RunWaitConditionResolveRequest.model_rebuild()
RunWaitConditionResponseBody.model_rebuild()
RunWaitConditionResponseMetadata.model_rebuild()
RunWaitConditionResponseResources.model_rebuild()
RunWaitConditionResponse.model_rebuild()
RunTemplateResponseBody.model_rebuild()
RunTemplateResponseMetadata.model_rebuild()
RunTemplateResponseResources.model_rebuild()
RunTemplateResponseBody.model_rebuild()
ScheduleResponseBody.model_rebuild()
ScheduleResponseMetadata.model_rebuild()
ScheduleResponseResources.model_rebuild()
SecretResponseBody.model_rebuild()
SecretResponseMetadata.model_rebuild()
SecretResponseResources.model_rebuild()
ServiceResponseBody.model_rebuild()
ServiceResponseMetadata.model_rebuild()
ServiceResponseResources.model_rebuild()
ServiceConnectorResponseBody.model_rebuild()
ServiceConnectorResponseMetadata.model_rebuild()
ServiceConnectorResponseResources.model_rebuild()
StackRequest.model_rebuild()
StackResponseBody.model_rebuild()
StackResponseMetadata.model_rebuild()
StackResponseResources.model_rebuild()
StepRunRequest.model_rebuild()
StepRunUpdate.model_rebuild()
StepRunResponseBody.model_rebuild()
StepRunResponseMetadata.model_rebuild()
StepRunResponseResources.model_rebuild()
TagResponseBody.model_rebuild()
TagResponseResources.model_rebuild()
ComponentInfo.model_rebuild()
ServiceConnectorInfo.model_rebuild()
ServiceConnectorResourcesInfo.model_rebuild()
ResourcesInfo.model_rebuild()
ResourcePoolResponseBody.model_rebuild()
ResourcePoolResponseMetadata.model_rebuild()
ResourcePoolResponseResources.model_rebuild()
ResourcePoolResponse.model_rebuild()
ResourceRequestResponseBody.model_rebuild()
ResourceRequestResponseMetadata.model_rebuild()
ResourceRequestResponseResources.model_rebuild()
ResourceRequestResponse.model_rebuild()
ResourcePoolAllocation.model_rebuild()
ResourcePoolQueueItem.model_rebuild()
ResourcePoolSubjectPolicyRequest.model_rebuild()
ResourcePoolSubjectPolicyResponseBody.model_rebuild()
ResourcePoolSubjectPolicyResponseMetadata.model_rebuild()
ResourcePoolSubjectPolicyResponseResources.model_rebuild()
ResourcePoolSubjectPolicyResponse.model_rebuild()
TriggerRequest.model_rebuild()
TriggerResponseBody.model_rebuild()
TriggerResponseMetadata.model_rebuild()
TriggerResponseResources.model_rebuild()
ScheduleTriggerRequest.model_rebuild()
ScheduleTriggerResponse.model_rebuild()
ScheduleTriggerResponseBody.model_rebuild()
ScheduleTriggerUpdate.model_rebuild()
PlatformEventTrigger.model_rebuild()
PlatformEventTriggerRequest.model_rebuild()
PlatformEventTriggerUpdate.model_rebuild()
PlatformEventTriggerResponse.model_rebuild()
PlatformEventTriggerResponseBody.model_rebuild()


__all__ = [
    # V2 Base
    "BaseRequest",
    "BaseResponse",
    "BaseUpdate",
    "BaseIdentifiedResponse",
    "BaseResponseBody",
    "BaseResponseMetadata",
    "BaseResponseResources",
    "BaseDatedResponseBody",
    "BaseZenModel",
    "UserScopedRequest",
    "UserScopedFilter",
    "UserScopedResponse",
    "UserScopedResponseBody",
    "UserScopedResponseMetadata",
    "ProjectScopedRequest",
    "ProjectScopedFilter",
    "ProjectScopedResponse",
    "ProjectScopedResponseBody",
    "ProjectScopedResponseMetadata",
    "ProjectScopedResponseResources",
    "ProjectScopedFilter",
    "BaseFilter",
    "StrFilter",
    "BoolFilter",
    "NumericFilter",
    "UUIDFilter",
    "TaggableFilter",
    "RunMetadataFilterMixin",
    "Page",
    # V2 Core
    "APIKey",
    "APIKeyRequest",
    "APIKeyUpdate",
    "APIKeyFilter",
    "APIKeyResponse",
    "APIKeyResponseBody",
    "APIKeyResponseMetadata",
    "APIKeyInternalResponse",
    "APIKeyInternalUpdate",
    "APIKeyRotateRequest",
    "ApiTransactionRequest",
    "ApiTransactionUpdate",
    "ApiTransactionResponse",
    "ApiTransactionResponseBody",
    "ApiTransactionResponseMetadata",
    "ApiTransactionResponseResources",
    "ArtifactFilter",
    "ArtifactRequest",
    "ArtifactResponse",
    "ArtifactResponseBody",
    "ArtifactResponseMetadata",
    "ArtifactResponseResources",
    "ArtifactUpdate",
    "ArtifactVersionRequest",
    "ArtifactVersionFilter",
    "ArtifactVersionResponse",
    "ArtifactVersionResponseBody",
    "ArtifactVersionResponseMetadata",
    "ArtifactVersionResponseResources",
    "ArtifactVersionUpdate",
    "ArtifactVisualizationRequest",
    "ArtifactVisualizationResponse",
    "ArtifactVisualizationResponseBody",
    "ArtifactVisualizationResponseMetadata",
    "ArtifactVisualizationResponseResources",
    "CodeReferenceRequest",
    "CodeReferenceResponse",
    "CodeReferenceResponseBody",
    "CodeReferenceResponseMetadata",
    "CodeRepositoryUpdate",
    "CodeRepositoryFilter",
    "CodeRepositoryRequest",
    "CodeRepositoryResponse",
    "CodeRepositoryResponseBody",
    "CodeRepositoryResponseMetadata",
    "CodeRepositoryResponseResources",
    "ComponentBase",
    "ComponentRequest",
    "ComponentUpdate",
    "ComponentFilter",
    "ComponentResponse",
    "ComponentResponseBody",
    "ComponentResponseMetadata",
    "ComponentResponseResources",
    "DefaultComponentRequest",
    "DefaultStackRequest",
    "DeploymentRequest",
    "DeploymentUpdate",
    "DeploymentFilter",
    "DeploymentOperationalState",
    "DeploymentResponse",
    "DeploymentResponseBody",
    "DeploymentResponseMetadata",
    "DeploymentResponseResources",
    "CuratedVisualizationRequest",
    "CuratedVisualizationResponse",
    "CuratedVisualizationResponseBody",
    "CuratedVisualizationResponseMetadata",
    "CuratedVisualizationResponseResources",
    "CuratedVisualizationUpdate",
    "FlavorRequest",
    "FlavorUpdate",
    "FlavorFilter",
    "FlavorResponse",
    "FlavorResponseBody",
    "FlavorResponseMetadata",
    "FlavorResponseResources",
    "HookInvocationRequest",
    "HookInvocationFilter",
    "HookInvocationResponse",
    "HookInvocationResponseBody",
    "HookInvocationResponseMetadata",
    "HookInvocationResponseResources",
    "LogsRequest",
    "LogsUpdate",
    "LogsResponse",
    "LogsResponseBody",
    "LogsResponseMetadata",
    "LogsResponseResources",
    "ModelFilter",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseBody",
    "ModelResponseMetadata",
    "ModelResponseResources",
    "ModelUpdate",
    "ModelVersionFilter",
    "ModelVersionRequest",
    "ModelVersionResponse",
    "ModelVersionResponseBody",
    "ModelVersionResponseMetadata",
    "ModelVersionResponseResources",
    "ModelVersionUpdate",
    "ModelVersionArtifactFilter",
    "ModelVersionArtifactRequest",
    "ModelVersionArtifactResponse",
    "ModelVersionArtifactResponseBody",
    "ModelVersionPipelineRunFilter",
    "ModelVersionPipelineRunRequest",
    "ModelVersionPipelineRunResponse",
    "ModelVersionPipelineRunResponseBody",
    "OAuthDeviceUpdate",
    "OAuthDeviceFilter",
    "OAuthDeviceResponse",
    "OAuthDeviceResponseBody",
    "OAuthDeviceResponseMetadata",
    "OAuthDeviceResponseResources",
    "OAuthDeviceInternalRequest",
    "OAuthDeviceInternalUpdate",
    "OAuthDeviceInternalResponse",
    "PipelineRequest",
    "PipelineUpdate",
    "PipelineFilter",
    "PipelineResponse",
    "PipelineResponseBody",
    "PipelineResponseMetadata",
    "PipelineResponseResources",
    "PipelineBuildBase",
    "PipelineBuildRequest",
    "PipelineBuildFilter",
    "PipelineBuildResponse",
    "PipelineBuildResponseBody",
    "PipelineBuildResponseMetadata",
    "PipelineBuildResponseResources",
    "PipelineSnapshotBase",
    "PipelineSnapshotRequest",
    "PipelineSnapshotUpdate",
    "PipelineSnapshotFilter",
    "PipelineSnapshotResponse",
    "PipelineSnapshotResponseBody",
    "PipelineSnapshotResponseMetadata",
    "PipelineSnapshotResponseResources",
    "PipelineSnapshotRunRequest",
    "PipelineRunRequest",
    "PipelineRunUpdate",
    "PipelineRunFilter",
    "PipelineRunResponse",
    "PipelineRunResponseBody",
    "PipelineRunResponseMetadata",
    "PipelineRunResponseResources",
    "PipelineRunTriggerInfo",
    "ResourcePoolRequest",
    "ResourcePoolUpdate",
    "ResourcePoolFilter",
    "ResourcePoolResponse",
    "ResourcePoolResponseBody",
    "ResourcePoolResponseMetadata",
    "ResourcePoolResponseResources",
    "ResourcePoolAllocation",
    "ResourcePoolQueueItem",
    "ResourcePoolSubjectPolicyFilter",
    "ResourcePoolSubjectPolicyRequest",
    "ResourcePoolSubjectPolicyResponse",
    "ResourcePoolSubjectPolicyResponseBody",
    "ResourcePoolSubjectPolicyResponseMetadata",
    "ResourcePoolSubjectPolicyResponseResources",
    "ResourcePoolSubjectPolicyUpdate",
    "ResourceRequestRequest",
    "ResourceRequestFilter",
    "ResourceRequestResponse",
    "ResourceRequestResponseBody",
    "ResourceRequestResponseMetadata",
    "ResourceRequestResponseResources",
    "RunTemplateRequest",
    "RunTemplateUpdate",
    "RunTemplateResponse",
    "RunTemplateResponseBody",
    "RunTemplateResponseMetadata",
    "RunTemplateResponseResources",
    "RunTemplateFilter",
    "RunWaitConditionFilter",
    "RunWaitConditionRequest",
    "RunWaitConditionResolveRequest",
    "RunWaitConditionResponse",
    "RunWaitConditionResponseBody",
    "RunWaitConditionResponseMetadata",
    "RunWaitConditionResponseResources",
    "RunWaitConditionLeaseUpdate",
    "RunMetadataRequest",
    "ScheduleRequest",
    "ScheduleUpdate",
    "ScheduleFilter",
    "ScheduleResponse",
    "ScheduleResponseBody",
    "ScheduleResponseMetadata",
    "ScheduleResponseResources",
    "SecretFilter",
    "SecretRequest",
    "SecretResponse",
    "SecretResponseBody",
    "SecretResponseMetadata",
    "SecretResponseResources",
    "SecretUpdate",
    "ServiceResponse",
    "ServiceResponseBody",
    "ServiceResponseMetadata",
    "ServiceUpdate",
    "ServiceFilter",
    "ServiceRequest",
    "ServiceResponseResources",
    "ServerActivationRequest",
    "ServerSettingsResponse",
    "ServerSettingsResponseResources",
    "ServerSettingsResponseBody",
    "ServerSettingsResponseMetadata",
    "ServerSettingsUpdate",
    "ServiceAccountFilter",
    "ServiceAccountResponseBody",
    "ServiceAccountResponseMetadata",
    "ServiceAccountUpdate",
    "ServiceAccountRequest",
    "ServiceAccountInternalRequest",
    "ServiceAccountInternalUpdate",
    "ServiceAccountResponse",
    "ServiceConnectorConfiguration",
    "ServiceConnectorRequest",
    "ServiceConnectorUpdate",
    "ServiceConnectorFilter",
    "ServiceConnectorResponse",
    "ServiceConnectorResponseBody",
    "ServiceConnectorResponseMetadata",
    "ServiceConnectorResponseResources",
    "StackRequest",
    "StackUpdate",
    "StackFilter",
    "StackResponse",
    "StackResponseBody",
    "StackResponseMetadata",
    "StackResponseResources",
    "StepRunRequest",
    "StepRunUpdate",
    "StepRunFilter",
    "StepRunResponse",
    "StepRunResponseBody",
    "StepRunResponseMetadata",
    "StepRunResponseResources",
    "StreamEvent",
    "StreamBatchRequest",
    "StreamBatchResponse",
    "TagFilter",
    "TagResourceResponse",
    "TagResourceResponseBody",
    "TagResourceRequest",
    "TagResponse",
    "TagResponseBody",
    "TagResponseMetadata",
    "TagResponseResources",
    "TagRequest",
    "TagUpdate",
    "UserRequest",
    "UserUpdate",
    "UserFilter",
    "UserResponse",
    "UserResponseBody",
    "UserResponseMetadata",
    "ProjectRequest",
    "ProjectUpdate",
    "ProjectFilter",
    "ProjectResponse",
    "ProjectResponseBody",
    "ProjectResponseMetadata",
    "TriggerRequest",
    "TriggerUpdate",
    "TriggerResponseBody",
    "TriggerResponseMetadata",
    "TriggerResponseResources",
    "TriggerFilter",
    "TriggerSnapshotDispatchState",
    "TriggerDispatchErrorSeverity",
    "TriggerDispatchStatusCode",
    # V2 Misc
    "AuthenticationMethodModel",
    "DeployedStack",
    "ServiceConnectorResourcesModel",
    "ServiceConnectorTypeModel",
    "ServiceConnectorTypedResourcesModel",
    "ServiceConnectorRequirements",
    "ResourceTypeModel",
    "UserAuthModel",
    "ExternalUserModel",
    "BuildItem",
    "LoadedVisualization",
    "ServerLoadInfo",
    "ServerModel",
    "ServerDatabaseType",
    "ServerDeploymentType",
    "ServerStatistics",
    "ServiceType",
    "StackDeploymentConfig",
    "StackDeploymentInfo",
    "OAuthDeviceAuthorizationRequest",
    "OAuthDeviceAuthorizationResponse",
    "OAuthDeviceTokenRequest",
    "OAuthDeviceUserAgentHeader",
    "OAuthDeviceVerificationRequest",
    "OAuthRedirectResponse",
    "OAuthTokenResponse",
    "ComponentInfo",
    "ServiceConnectorInfo",
    "ServiceConnectorResourcesInfo",
    "TagResource",
    "ResourcesInfo",
    "RunMetadataEntry",
    "RunMetadataResource",
    "ProjectStatistics",
    "MetadataGrouping",
    "MetadataMetric",
    "RunStatisticsGroup",
    "RunStatisticsRequest",
    "RunStatisticsResponse",
    "SimpleGrouping",
    "SimpleMetric",
    "StatisticsAggregation",
    "StatisticsGrouping",
    "StatisticsGroupingType",
    "StatisticsMetric",
    "StatisticsMetricSource",
    "StatisticsTimeGranularity",
    "TimeGrouping",
    "PipelineRunDAG",
    "ExceptionInfo",
    "PipelineRunIdentifier",
    "StepRunIdentifier",
    "ArtifactVersionIdentifier",
    "ModelVersionIdentifier",
    "StepHeartbeatResponse",
    "ScheduleTriggerRequest",
    "ScheduleTriggerResponse",
    "ScheduleTriggerResponseBody",
    "ScheduleTriggerUpdate",
    "PlatformEventTriggerRequest",
    "PlatformEventTriggerUpdate",
    "PlatformEventTriggerResponse",
    "PlatformEventTriggerResponseBody",
    "PlatformEventTrigger",
    "TRIGGER_UPDATE_TYPE_UNION",
    "TRIGGER_CREATE_TYPE_UNION",
    "TRIGGER_RETURN_TYPE_UNION",
    "SourceEntity",
    "TriggerExecutionInfo",
]
