# Changes here will be overwritten by Copier
_commit: 2025.09.22
_src_path: gh:zenml-io/template-e2e-batch
data_quality_checks: true
email: info@zenml.io
full_name: ZenML GmbH
hyperparameters_tuning: true
metric_compare_promotion: true
notify_on_failures: true
notify_on_successes: false
open_source_license: apache
product_name: e2e_use_case
project_name: ZenML E2E project
target_environment: staging
version: 0.0.1
zenml_server_url: ''
