---
name: Check Markdown Links
on:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install PyGithub
      - name: Run markdown link checker
        run: ./scripts/check_broken_links.sh docs
        env:
          GITHUB_TOKEN: ${{ github.event.pull_request.head.repo.fork == false && secrets.GITHUB_TOKEN ||  '' }}
