---
name: Check Markdown Links
on:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install PyGithub
      - name: Run markdown link checker
        run: ./scripts/check_broken_links.sh docs
        env:
          GITHUB_TOKEN: ${{ github.event.pull_request.head.repo.fork == false && secrets.GITHUB_TOKEN ||  '' }}
