---
# https://github.com/marketplace/actions/team-labeler-action
# https://github.com/TimonVS/pr-labeler-action
on:
  pull_request:
    types: [opened]
name: pr-label
jobs:
  pr-labeler:
    if: github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: JulienKode/team-labeler-action@edc2a1d3b252624ac7611293835edad9f1392ed4  # v2.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af  # v5.0.0
        with:
          configuration-path: .github/branch-labels.yml
