---
# https://github.com/marketplace/actions/team-labeler-action
# https://github.com/TimonVS/pr-labeler-action
on:
  pull_request:
    types: [opened]
name: pr-label
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
env:
  ZENML_DEBUG: 1
  ZENML_LOGGING_VERBOSITY: debug
  ZENML_ANALYTICS_OPT_IN: false
jobs:
  pr-labeler:
    if: github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: JulienKode/team-labeler-action@e912b4b3a2e329a4dc6ad282cfecad79cab8fe81  # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af  # v5.0.0
        with:
          configuration-path: .github/branch-labels.yml
