---
# package and push the zenml helm chart to the ECR repository
name: Publish Helm Chart
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish_to_ecr:
    name: Publish Helm Chart 🛞 to ECR ☁️
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      # The following sed command replaces the version number in Chart.yaml with the tag version.
      # It replaces the line that starts with "version: " with "version: <tag version>"
      - name: Add tag version to Chart.yaml
        run: |
          sed -i "s/version: .*/version: \"${GITHUB_REF_NAME}\"/" helm/Chart.yaml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b  # v6.2.0
        with:
          role-to-assume: arn:aws:iam::715803424590:role/gh-action-role-zenml-helm
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64  # v2.1.6
        with:
          mask-password: 'true'
          registry-type: public

      # TODO: revisit the pinned helm version + find a higher version
      - name: install helm with version 3.9.2
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310  # v5.0.1
        with:
          version: v3.9.2  # default is latest (stable)
        id: install-helm
      - name: Package and push helm chart to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: zenml
          REPOSITORY: zenml
        run: |-
          helm package ./helm
          helm push $REPOSITORY-${GITHUB_REF_NAME}.tgz oci://$REGISTRY/$REGISTRY_ALIAS
