---
name: Publish SDK Docs
on:
  push:
    branches: [release/**]
jobs:
  publish:
    name: Build 🔨 and publish 📰 the api docs 📁 to gh-pages
    if: github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0  # fetch all commits/branches including gh-pages
      - name: Get the version from the github branch name
        id: get_version
        run: |
          BRANCH='${GITHUB_REF_NAME}'
          echo ::set-output name=VERSION::${BRANCH#release/}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
        with:
          node-version: '14'
      - run: npm install
      - run: npm install html-minifier -g
      - name: Set up Python 3.11
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.11'
      - name: Setup git user
        run: |
          git config --global user.name 'Code Monkey'
          git config --global user.email 'codemonkey@zenml.io'
      - name: Runs docs generation
        run: |-
          bash scripts/generate-docs.sh -s src/zenml/ --push --latest -v ${STEPS_GET_VERSION_OUTPUTS_VERSION}
        env:
          STEPS_GET_VERSION_OUTPUTS_VERSION: ${{ steps.get_version.outputs.VERSION }}
