---
name: Publish Pypi package
on:
  workflow_call:
jobs:
  publish_to_pypi:
    name: Publish Python 🐍 package 📦 to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # This permission is required for trusted publishing.
      id-token: write
      contents: read
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Get the version from the github tag ref
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b  # v7.3.0
        with:
          version: 0.8.14
          enable-cache: false
      - name: Include latest dashboard
        run: bash scripts/install-dashboard.sh
      - name: Verify version
        run: |-
          if [ "$(cat src/zenml/VERSION)" != "$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')" ]; then
            echo "Version mismatch between src/zenml/VERSION and git tag"
            exit 1
          fi
      - name: Build package
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # release/v1
