---
name: Publish Cloud Stack Templates
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish_stack_templates:
    name: Publish Cloud Stack Templates
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      # Setup AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b  # v6.2.0
        with:
          role-to-assume: arn:aws:iam::715803424590:role/gh-action-role-zenml-stack-cf-templates
          aws-region: eu-central-1
      # Publish the CloudFormation template to S3
      - name: Push CloudFormation template to S3
        run: |-
          aws s3 cp infra/aws/aws-ecr-s3-sagemaker.yaml s3://zenml-cf-templates/aws-ecr-s3-sagemaker.yaml
