---
name: Spellcheck
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore: ['*', '!pyproject.toml']
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ['*', '!pyproject.toml']
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  spellcheck:
    if: github.event.pull_request.draft == false && github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Spelling checker
        uses: crate-ci/typos@37bb98842b0d8c4ffebdb75301a13db0267cef89  # v1.47.2
        with:
          files: .
          config: ./.typos.toml
