---
name: Spellcheck
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore: ['*', '!pyproject.toml']
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ['*', '!pyproject.toml']
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  spellcheck:
    if: github.event.pull_request.draft == false && github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Spelling checker
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b  # v1.50.1
        with:
          files: .
          config: ./.typos.toml
