---
name: Spellcheck
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore: ['*', '!pyproject.toml']
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: ['*', '!pyproject.toml']
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  spellcheck:
    if: github.event.pull_request.draft == false && github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Spelling checker
        uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d  # v1.44.0
        with:
          files: .
          config: ./.typos.toml
