---
name: ci-fast-test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore: [docs/**, "*", "!pyproject.toml", "**.md"]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: [docs/**, "*", "!pyproject.toml", "**.md"]
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ubuntu-latest-integration-test:
    needs: [linting]
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        # IMPORTANT: Since we are using the combination of `arc-runner-set`
        # and `3.10` in our `ci-fast` workflow, this combination has been
        # excluded from the `ci-slow` workflow. If you change the configuration
        # here, please adjust the configuration of `ci-slow` accordingly.
        os: [ubuntu-latest]
        python-version: ["3.11"]
        test_environment: [default, docker-server-docker-orchestrator-mysql]
      fail-fast: false
    uses: ./.github/workflows/integration-test-fast.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit
