---
name: Trivy ZenServer Scan
on:
  push:
    branches: [main]
  schedule:
    - cron: 0 4 * * 1  # At 04:00 on Monday
jobs:
  trivy-scan:
    name: Trivy ZenServer scan & analysis
    if: github.repository == 'zenml-io/zenml'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: zenserver-Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        with:
          image-ref: docker.io/zenmldocker/zenml-server:latest
          format: sarif
          output: trivy-results-zenserver.sarif
          # Ignore unfixed vulnerabilities (i.e. vulnerabilities that have no
          # fix available and that we can't fix by updating the container
          # packages)
          ignore-unfixed: true
      - name: Upload Trivy zenserver scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e  # v4.36.2
        with:
          sarif_file: trivy-results-zenserver.sarif
